// 日常英语词库 · 厨房与烹饪（DK 图解词典 第 27–29 单元）
// 数据格式：{ id, theme, word, cn（中文释义）, ex（例句，可为空） }
// 说明：英式/美式并存的词，取常用形式；动词带例句以支持“选词填空”。

export const THEME_ORDER = ["厨房器具", "餐具", "厨具", "烹饪", "烘焙"];

export const VOCAB = [
  // ── 27.1 厨房器具 ──
  { id: 0, theme: "厨房器具", word: "mixer", cn: "搅拌机", ex: "" },
  { id: 1, theme: "厨房器具", word: "toaster", cn: "烤面包机", ex: "" },
  { id: 2, theme: "厨房器具", word: "blender", cn: "食品加工器，搅拌机", ex: "" },
  { id: 3, theme: "厨房器具", word: "dishwasher", cn: "洗碗机", ex: "" },
  { id: 4, theme: "厨房器具", word: "electric kettle", cn: "电热水壶", ex: "" },
  { id: 5, theme: "厨房器具", word: "rice cooker", cn: "电饭煲", ex: "" },
  { id: 6, theme: "厨房器具", word: "freezer", cn: "冷冻室", ex: "" },
  { id: 7, theme: "厨房器具", word: "ice maker", cn: "制冰机", ex: "" },
  { id: 8, theme: "厨房器具", word: "shelf", cn: "搁板", ex: "" },
  { id: 9, theme: "厨房器具", word: "crisper", cn: "蔬果保鲜格", ex: "" },
  { id: 10, theme: "厨房器具", word: "refrigerator", cn: "冰箱（英式 fridge）", ex: "" },
  { id: 11, theme: "厨房器具", word: "pantry", cn: "食品储物柜", ex: "" },
  { id: 12, theme: "厨房器具", word: "ceramic stovetop", cn: "陶瓷炉台", ex: "" },
  { id: 13, theme: "厨房器具", word: "exhaust fan", cn: "排气扇", ex: "" },
  { id: 14, theme: "厨房器具", word: "dish rack", cn: "碗碟架", ex: "" },
  { id: 15, theme: "厨房器具", word: "shelves", cn: "搁架", ex: "" },
  { id: 16, theme: "厨房器具", word: "microwave oven", cn: "微波炉", ex: "" },
  { id: 17, theme: "厨房器具", word: "backsplash", cn: "防溅挡板", ex: "" },
  { id: 18, theme: "厨房器具", word: "burner", cn: "火炉，灶头", ex: "" },
  { id: 19, theme: "厨房器具", word: "countertop", cn: "操作台（英式 worktop）", ex: "" },
  { id: 20, theme: "厨房器具", word: "faucet", cn: "水龙头（英式 tap）", ex: "" },
  { id: 21, theme: "厨房器具", word: "drawer", cn: "抽屉", ex: "" },
  { id: 22, theme: "厨房器具", word: "cabinet", cn: "橱柜", ex: "" },
  { id: 23, theme: "厨房器具", word: "oven", cn: "烤箱", ex: "" },
  { id: 24, theme: "厨房器具", word: "stove", cn: "炉盘（英式 hob）", ex: "" },
  { id: 25, theme: "厨房器具", word: "trash can", cn: "垃圾桶（英式 rubbish bin）", ex: "" },
  { id: 26, theme: "厨房器具", word: "sink", cn: "洗涤槽，水槽", ex: "" },

  // ── 27.2 餐具 ──
  { id: 27, theme: "餐具", word: "fork", cn: "叉子", ex: "" },
  { id: 28, theme: "餐具", word: "knife", cn: "刀", ex: "" },
  { id: 29, theme: "餐具", word: "tablespoon", cn: "餐匙，大汤匙", ex: "" },
  { id: 30, theme: "餐具", word: "teaspoon", cn: "茶匙", ex: "" },
  { id: 31, theme: "餐具", word: "soup spoon", cn: "汤匙", ex: "" },
  { id: 32, theme: "餐具", word: "serving spoon", cn: "分餐匙", ex: "" },
  { id: 33, theme: "餐具", word: "silverware", cn: "餐具（英式 cutlery）", ex: "" },
  { id: 34, theme: "餐具", word: "butter knife", cn: "黄油刀", ex: "" },
  { id: 35, theme: "餐具", word: "chopsticks", cn: "筷子", ex: "" },
  { id: 36, theme: "餐具", word: "ladle", cn: "长柄勺", ex: "" },
  { id: 37, theme: "餐具", word: "dinner plate", cn: "正餐用盘", ex: "" },
  { id: 38, theme: "餐具", word: "side plate", cn: "甜点盘，小盘", ex: "" },
  { id: 39, theme: "餐具", word: "dinnerware", cn: "正餐餐具（英式 crockery）", ex: "" },
  { id: 40, theme: "餐具", word: "coffee cup", cn: "咖啡杯", ex: "" },
  { id: 41, theme: "餐具", word: "teacup", cn: "茶杯", ex: "" },
  { id: 42, theme: "餐具", word: "mug", cn: "马克杯", ex: "" },
  { id: 43, theme: "餐具", word: "espresso maker", cn: "浓缩咖啡机", ex: "" },
  { id: 44, theme: "餐具", word: "teapot", cn: "茶壶", ex: "" },
  { id: 45, theme: "餐具", word: "place setting", cn: "一套餐具", ex: "" },
  { id: 46, theme: "餐具", word: "napkin", cn: "餐巾", ex: "" },
  { id: 47, theme: "餐具", word: "napkin ring", cn: "餐巾环", ex: "" },
  { id: 48, theme: "餐具", word: "bowl", cn: "碗", ex: "" },
  { id: 49, theme: "餐具", word: "soup bowl", cn: "汤碗", ex: "" },
  { id: 50, theme: "餐具", word: "rice bowl", cn: "饭碗", ex: "" },
  { id: 51, theme: "餐具", word: "egg cup", cn: "蛋杯", ex: "" },
  { id: 52, theme: "餐具", word: "sushi set", cn: "寿司餐具", ex: "" },
  { id: 53, theme: "餐具", word: "measuring cup", cn: "量杯", ex: "" },
  { id: 54, theme: "餐具", word: "tumbler", cn: "平底玻璃杯", ex: "" },
  { id: 55, theme: "餐具", word: "wineglass", cn: "葡萄酒杯", ex: "" },
  { id: 56, theme: "餐具", word: "pint glass", cn: "品脱杯", ex: "" },
  { id: 57, theme: "餐具", word: "stemware", cn: "高脚器皿", ex: "" },
  { id: 58, theme: "餐具", word: "glassware", cn: "玻璃器皿", ex: "" },
  { id: 59, theme: "餐具", word: "jar", cn: "罐子", ex: "" },
  { id: 60, theme: "餐具", word: "beaker", cn: "大口杯", ex: "" },
  { id: 61, theme: "餐具", word: "sake cup", cn: "清酒杯", ex: "" },
  { id: 62, theme: "餐具", word: "coaster", cn: "杯垫", ex: "" },

  // ── 28 厨具 ──
  { id: 63, theme: "厨具", word: "grater", cn: "擦丝器，礤床", ex: "" },
  { id: 64, theme: "厨具", word: "peeler", cn: "削皮刀", ex: "" },
  { id: 65, theme: "厨具", word: "whisk", cn: "打蛋器", ex: "" },
  { id: 66, theme: "厨具", word: "kitchen knife", cn: "厨刀", ex: "" },
  { id: 67, theme: "厨具", word: "bread knife", cn: "面包刀", ex: "" },
  { id: 68, theme: "厨具", word: "kitchen scissors", cn: "厨房剪刀", ex: "" },
  { id: 69, theme: "厨具", word: "cleaver", cn: "切肉刀，剁刀", ex: "" },
  { id: 70, theme: "厨具", word: "knife sharpener", cn: "磨刀器", ex: "" },
  { id: 71, theme: "厨具", word: "meat tenderizer", cn: "松肉槌", ex: "" },
  { id: 72, theme: "厨具", word: "skewer", cn: "串肉扦", ex: "" },
  { id: 73, theme: "厨具", word: "can opener", cn: "开罐器（英式 tin opener）", ex: "" },
  { id: 74, theme: "厨具", word: "cutting board", cn: "案板，切菜板（英式 chopping board）", ex: "" },
  { id: 75, theme: "厨具", word: "bottle opener", cn: "开瓶器", ex: "" },
  { id: 76, theme: "厨具", word: "corkscrew", cn: "瓶塞钻，开酒器", ex: "" },
  { id: 77, theme: "厨具", word: "wooden spoon", cn: "木勺", ex: "" },
  { id: 78, theme: "厨具", word: "slotted spoon", cn: "漏勺", ex: "" },
  { id: 79, theme: "厨具", word: "spatula", cn: "刮铲，抹刀", ex: "" },
  { id: 80, theme: "厨具", word: "apple corer", cn: "苹果去核器", ex: "" },
  { id: 81, theme: "厨具", word: "masher", cn: "捣泥器", ex: "" },
  { id: 82, theme: "厨具", word: "garlic press", cn: "压蒜器", ex: "" },
  { id: 83, theme: "厨具", word: "carving fork", cn: "切肉叉", ex: "" },
  { id: 84, theme: "厨具", word: "scoop", cn: "深口圆匙，勺", ex: "" },
  { id: 85, theme: "厨具", word: "handle", cn: "锅柄，把手", ex: "" },
  { id: 86, theme: "厨具", word: "lid", cn: "锅盖，盖子", ex: "" },
  { id: 87, theme: "厨具", word: "saucepan", cn: "长柄深平底锅", ex: "" },
  { id: 88, theme: "厨具", word: "frying pan", cn: "平底锅，煎锅", ex: "" },
  { id: 89, theme: "厨具", word: "griddle pan", cn: "煎锅，烤盘锅", ex: "" },
  { id: 90, theme: "厨具", word: "wok", cn: "炒锅", ex: "" },
  { id: 91, theme: "厨具", word: "colander", cn: "滤盆，笊篱", ex: "" },
  { id: 92, theme: "厨具", word: "turner", cn: "煎鱼铲，锅铲（英式 fish slice）", ex: "" },
  { id: 93, theme: "厨具", word: "sieve", cn: "筛网", ex: "" },
  { id: 94, theme: "厨具", word: "measuring spoons", cn: "量匙", ex: "" },
  { id: 95, theme: "厨具", word: "mortar", cn: "研钵", ex: "" },
  { id: 96, theme: "厨具", word: "pestle", cn: "研杵", ex: "" },
  { id: 97, theme: "厨具", word: "mortar and pestle", cn: "研磨杵钵", ex: "" },
  { id: 98, theme: "厨具", word: "tagine", cn: "塔吉锅", ex: "" },
  { id: 99, theme: "厨具", word: "mixing bowl", cn: "搅拌碗", ex: "" },
  { id: 100, theme: "厨具", word: "soufflé dish", cn: "舒芙蕾烤模", ex: "" },
  { id: 101, theme: "厨具", word: "ramekin", cn: "干酪蛋糕模，小烤盅", ex: "" },
  { id: 102, theme: "厨具", word: "casserole dish", cn: "砂锅，炖锅", ex: "" },
  { id: 103, theme: "厨具", word: "frying basket", cn: "炸篮", ex: "" },
  { id: 104, theme: "厨具", word: "butter dish", cn: "黄油盘", ex: "" },
  { id: 105, theme: "厨具", word: "timer", cn: "计时器", ex: "" },
  { id: 106, theme: "厨具", word: "egg timer", cn: "煮蛋计时器", ex: "" },
  { id: 107, theme: "厨具", word: "lemon squeezer", cn: "柠檬榨汁器", ex: "" },
  { id: 108, theme: "厨具", word: "coffee press", cn: "法式滤压壶", ex: "" },
  { id: 109, theme: "厨具", word: "meat thermometer", cn: "肉类温度计", ex: "" },
  { id: 110, theme: "厨具", word: "cake pan", cn: "蛋糕烤盘（英式 cake tin）", ex: "" },
  { id: 111, theme: "厨具", word: "skillet", cn: "长柄平底煎锅", ex: "" },
  { id: 112, theme: "厨具", word: "glass baking dish", cn: "玻璃烤盘", ex: "" },
  { id: 113, theme: "厨具", word: "tongs", cn: "夹具，夹钳", ex: "" },
  { id: 114, theme: "厨具", word: "strainer", cn: "滤网", ex: "" },
  { id: 115, theme: "厨具", word: "mandoline", cn: "切片器", ex: "" },
  { id: 116, theme: "厨具", word: "knife stand", cn: "刀架", ex: "" },
  { id: 117, theme: "厨具", word: "pizza cutter", cn: "比萨刀", ex: "" },
  { id: 118, theme: "厨具", word: "dishcloth", cn: "洗碗布（英式 tea towel）", ex: "" },
  { id: 119, theme: "厨具", word: "egg slicer", cn: "鸡蛋切片器", ex: "" },
  { id: 120, theme: "厨具", word: "pressure cooker", cn: "高压锅", ex: "" },

  // ── 29.1 烹饪（动词与用量）──
  { id: 121, theme: "烹饪", word: "to sprinkle", cn: "洒，撒", ex: "Sprinkle some salt on top." },
  { id: 122, theme: "烹饪", word: "to bake", cn: "烘焙，烤", ex: "She likes to bake bread on weekends." },
  { id: 123, theme: "烹饪", word: "to garnish", cn: "装饰（菜肴）", ex: "Garnish the dish with fresh herbs." },
  { id: 124, theme: "烹饪", word: "to grease", cn: "涂油", ex: "Grease the pan before baking." },
  { id: 125, theme: "烹饪", word: "to roll", cn: "擀", ex: "Roll out the dough thinly." },
  { id: 126, theme: "烹饪", word: "to taste", cn: "尝", ex: "Taste the soup and add salt if needed." },
  { id: 127, theme: "烹饪", word: "to stir-fry", cn: "炒", ex: "Stir-fry the vegetables over high heat." },
  { id: 128, theme: "烹饪", word: "to chop", cn: "剁，切碎", ex: "Chop the onions finely." },
  { id: 129, theme: "烹饪", word: "to broil", cn: "烧烤（英式 to grill）", ex: "Broil the steak for a few minutes." },
  { id: 130, theme: "烹饪", word: "to roast", cn: "烤制", ex: "Roast the chicken for an hour." },
  { id: 131, theme: "烹饪", word: "to fry", cn: "油炸，煎", ex: "Fry the egg in a little oil." },
  { id: 132, theme: "烹饪", word: "to poach", cn: "沸水煮，水波", ex: "Poach the eggs in simmering water." },
  { id: 133, theme: "烹饪", word: "to simmer", cn: "煨，用文火慢煮", ex: "Let the sauce simmer for ten minutes." },
  { id: 134, theme: "烹饪", word: "to boil", cn: "煮沸", ex: "Boil the water before adding the pasta." },
  { id: 135, theme: "烹饪", word: "to freeze", cn: "冷冻", ex: "Freeze the leftovers for later." },
  { id: 136, theme: "烹饪", word: "to add", cn: "添加", ex: "Add a spoonful of sugar." },
  { id: 137, theme: "烹饪", word: "to mix", cn: "搅拌，混合", ex: "Mix the flour and eggs together." },
  { id: 138, theme: "烹饪", word: "to stir", cn: "搅动", ex: "Stir the soup so it doesn't burn." },
  { id: 139, theme: "烹饪", word: "to whisk", cn: "搅打", ex: "Whisk the eggs until fluffy." },
  { id: 140, theme: "烹饪", word: "to mash", cn: "捣成糊，捣烂", ex: "Mash the potatoes with butter." },
  { id: 141, theme: "烹饪", word: "to slice", cn: "切片", ex: "Slice the bread thinly." },
  { id: 142, theme: "烹饪", word: "to mince", cn: "绞，切成末", ex: "Mince the garlic finely." },
  { id: 143, theme: "烹饪", word: "to peel", cn: "去皮，削皮", ex: "Peel the potatoes before cooking." },
  { id: 144, theme: "烹饪", word: "to cut", cn: "切", ex: "Cut the cake into eight pieces." },
  { id: 145, theme: "烹饪", word: "to grate", cn: "擦丝，磨碎", ex: "Grate some cheese over the pasta." },
  { id: 146, theme: "烹饪", word: "to pour", cn: "倒", ex: "Pour the milk into the bowl." },
  { id: 147, theme: "烹饪", word: "to steam", cn: "蒸", ex: "Steam the vegetables for five minutes." },
  { id: 148, theme: "烹饪", word: "to beat eggs", cn: "打鸡蛋", ex: "" },
  { id: 149, theme: "烹饪", word: "to microwave", cn: "微波加热", ex: "Microwave it for one minute." },
  { id: 150, theme: "烹饪", word: "to melt butter", cn: "融化黄油", ex: "" },
  { id: 151, theme: "烹饪", word: "to carve", cn: "切块，把（肉）切开", ex: "Carve the roast turkey at the table." },
  { id: 152, theme: "烹饪", word: "to dice", cn: "切丁", ex: "Dice the carrots into small cubes." },
  { id: 153, theme: "烹饪", word: "to burn", cn: "烧糊，烧焦", ex: "Don't burn the onions." },
  { id: 154, theme: "烹饪", word: "to sauté", cn: "煸，嫩煎", ex: "Sauté the mushrooms in butter." },
  { id: 155, theme: "烹饪", word: "a pinch", cn: "一撮，少量", ex: "Add a pinch of salt." },
  { id: 156, theme: "烹饪", word: "a dash", cn: "少许", ex: "Add a dash of pepper." },
  { id: 157, theme: "烹饪", word: "a handful", cn: "一把", ex: "Add a handful of nuts." },

  // ── 29.2 烘焙 ──
  { id: 158, theme: "烘焙", word: "apron", cn: "围裙", ex: "" },
  { id: 159, theme: "烘焙", word: "oven mitt", cn: "烤箱手套（英式 oven glove）", ex: "" },
  { id: 160, theme: "烘焙", word: "flan pan", cn: "馅饼盘（英式 flan tin）", ex: "" },
  { id: 161, theme: "烘焙", word: "pie pan", cn: "派烤盘（英式 pie dish）", ex: "" },
  { id: 162, theme: "烘焙", word: "pastry brush", cn: "面粉刷，油刷", ex: "" },
  { id: 163, theme: "烘焙", word: "rolling pin", cn: "擀面杖", ex: "" },
  { id: 164, theme: "烘焙", word: "baking pan", cn: "烤盘（英式 baking tray）", ex: "" },
  { id: 165, theme: "烘焙", word: "muffin tin", cn: "麦芬烤盘（英式 muffin tray）", ex: "" },
  { id: 166, theme: "烘焙", word: "cooling rack", cn: "冷却架", ex: "" },
  { id: 167, theme: "烘焙", word: "icing", cn: "糖霜", ex: "" },
  { id: 168, theme: "烘焙", word: "piping bag", cn: "裱花袋", ex: "" },
  { id: 169, theme: "烘焙", word: "scales", cn: "秤，天平", ex: "" },
  { id: 170, theme: "烘焙", word: "to decorate", cn: "装饰", ex: "Decorate the cake with fresh fruit." },
];
