// 日常英语词库（从 DK 图解词典整理，按主题分组）
// 由 index.html 的 SEED_GROUPS 生成，共 322 词，12 个主题。
// 数据格式：{ id, theme, word, cn（中文释义）, ex（例句，可为空） }

export const THEME_ORDER = ["身体","厨房餐具","卧室","浴室","工具","衣服鞋子","医疗健康","城镇购物","蔬菜","水果","咖啡厅","早餐"];

export const VOCAB = [
  { id: 0, theme: "身体", word: "head", cn: "头", ex: "She nodded her head." },
  { id: 1, theme: "身体", word: "shoulder", cn: "肩膀", ex: "He carried the bag on his shoulder." },
  { id: 2, theme: "身体", word: "chest", cn: "胸部", ex: "He felt a pain in his chest." },
  { id: 3, theme: "身体", word: "arm", cn: "手臂", ex: "She broke her arm last week." },
  { id: 4, theme: "身体", word: "abdomen", cn: "腹部", ex: "The doctor pressed on his abdomen." },
  { id: 5, theme: "身体", word: "hand", cn: "手", ex: "Raise your hand if you know." },
  { id: 6, theme: "身体", word: "thigh", cn: "大腿", ex: "The runner has strong thighs." },
  { id: 7, theme: "身体", word: "leg", cn: "腿", ex: "My legs are tired after the walk." },
  { id: 8, theme: "身体", word: "foot", cn: "脚", ex: "She hurt her foot playing soccer." },
  { id: 9, theme: "身体", word: "calf", cn: "小腿肚", ex: "He got a cramp in his calf." },
  { id: 10, theme: "身体", word: "heel", cn: "脚后跟", ex: "These new shoes hurt my heel." },
  { id: 11, theme: "身体", word: "neck", cn: "脖子", ex: "She wore a scarf around her neck." },
  { id: 12, theme: "身体", word: "armpit", cn: "腋窝", ex: "" },
  { id: 13, theme: "身体", word: "elbow", cn: "肘", ex: "He leaned on his elbow." },
  { id: 14, theme: "身体", word: "waist", cn: "腰", ex: "The skirt is tight at the waist." },
  { id: 15, theme: "身体", word: "forearm", cn: "前臂", ex: "He has a tattoo on his forearm." },
  { id: 16, theme: "身体", word: "wrist", cn: "手腕", ex: "She wears a watch on her wrist." },
  { id: 17, theme: "身体", word: "hip", cn: "髋，臀部", ex: "She put her hands on her hips." },
  { id: 18, theme: "身体", word: "navel", cn: "肚脐", ex: "" },
  { id: 19, theme: "身体", word: "knee", cn: "膝盖", ex: "He fell and hurt his knee." },
  { id: 20, theme: "身体", word: "shin", cn: "小腿，胫", ex: "I banged my shin on the table." },
  { id: 21, theme: "身体", word: "ankle", cn: "脚踝", ex: "She twisted her ankle." },
  { id: 22, theme: "身体", word: "eyelid", cn: "眼睑", ex: "" },
  { id: 23, theme: "身体", word: "hair", cn: "头发", ex: "She has long black hair." },
  { id: 24, theme: "身体", word: "temple", cn: "太阳穴", ex: "He rubbed his temples." },
  { id: 25, theme: "身体", word: "cheek", cn: "脸颊", ex: "The baby has rosy cheeks." },
  { id: 26, theme: "身体", word: "lips", cn: "嘴唇", ex: "Her lips were dry." },
  { id: 27, theme: "身体", word: "jaw", cn: "下颚", ex: "He clenched his jaw." },
  { id: 28, theme: "身体", word: "forehead", cn: "额头", ex: "She wiped her forehead." },
  { id: 29, theme: "身体", word: "eyebrow", cn: "眉毛", ex: "He raised an eyebrow." },
  { id: 30, theme: "身体", word: "skin", cn: "皮肤", ex: "She has soft skin." },
  { id: 31, theme: "身体", word: "chin", cn: "下巴", ex: "He rested his chin on his hand." },
  { id: 32, theme: "身体", word: "eye", cn: "眼睛", ex: "Close your eyes." },
  { id: 33, theme: "身体", word: "ear", cn: "耳朵", ex: "The rabbit has long ears." },
  { id: 34, theme: "身体", word: "nose", cn: "鼻子", ex: "My nose is blocked." },
  { id: 35, theme: "身体", word: "nostril", cn: "鼻孔", ex: "" },
  { id: 36, theme: "身体", word: "mouth", cn: "嘴", ex: "Open your mouth." },
  { id: 37, theme: "身体", word: "teeth", cn: "牙齿", ex: "Brush your teeth twice a day." },
  { id: 38, theme: "身体", word: "eyelashes", cn: "睫毛", ex: "She has long eyelashes." },
  { id: 39, theme: "身体", word: "iris", cn: "虹膜", ex: "" },
  { id: 40, theme: "身体", word: "pupil", cn: "瞳孔", ex: "The pupil widens in the dark." },
  { id: 41, theme: "身体", word: "palm", cn: "手掌", ex: "He held the coin in his palm." },
  { id: 42, theme: "身体", word: "thumb", cn: "拇指", ex: "She gave a thumbs up." },
  { id: 43, theme: "身体", word: "index finger", cn: "食指", ex: "Point with your index finger." },
  { id: 44, theme: "身体", word: "middle finger", cn: "中指", ex: "" },
  { id: 45, theme: "身体", word: "ring finger", cn: "无名指", ex: "She wears a ring on her ring finger." },
  { id: 46, theme: "身体", word: "little finger", cn: "小指", ex: "" },
  { id: 47, theme: "身体", word: "fingernail", cn: "指甲", ex: "Don't bite your fingernails." },
  { id: 48, theme: "身体", word: "knuckle", cn: "指关节", ex: "He cracked his knuckles." },
  { id: 49, theme: "身体", word: "fist", cn: "拳头", ex: "He made a fist." },
  { id: 50, theme: "身体", word: "to smile", cn: "微笑", ex: "She smiled at me." },
  { id: 51, theme: "身体", word: "to grin", cn: "咧嘴笑", ex: "He grinned with joy." },
  { id: 52, theme: "身体", word: "to frown", cn: "皱眉", ex: "She frowned at the noise." },
  { id: 53, theme: "身体", word: "to wink", cn: "眨眼示意", ex: "He winked at her." },
  { id: 54, theme: "身体", word: "to blink", cn: "眨眼", ex: "She blinked in the bright light." },
  { id: 55, theme: "身体", word: "to blush", cn: "脸红", ex: "He blushed when praised." },
  { id: 56, theme: "身体", word: "to yawn", cn: "打哈欠", ex: "I yawned during the meeting." },
  { id: 57, theme: "身体", word: "to snore", cn: "打呼噜", ex: "He snores loudly at night." },
  { id: 58, theme: "身体", word: "to lick", cn: "舔", ex: "The dog licked my hand." },
  { id: 59, theme: "身体", word: "to breathe", cn: "呼吸", ex: "Breathe in deeply and relax." },
  { id: 60, theme: "厨房餐具", word: "toaster", cn: "烤面包机", ex: "Put the bread in the toaster." },
  { id: 61, theme: "厨房餐具", word: "blender", cn: "搅拌机，榨汁机", ex: "She made a smoothie in the blender." },
  { id: 62, theme: "厨房餐具", word: "dishwasher", cn: "洗碗机", ex: "Load the dishes into the dishwasher." },
  { id: 63, theme: "厨房餐具", word: "kettle", cn: "水壶", ex: "I boiled the kettle for tea." },
  { id: 64, theme: "厨房餐具", word: "rice cooker", cn: "电饭煲", ex: "" },
  { id: 65, theme: "厨房餐具", word: "freezer", cn: "冷冻室", ex: "Keep the ice cream in the freezer." },
  { id: 66, theme: "厨房餐具", word: "fridge", cn: "冰箱", ex: "Put the milk in the fridge." },
  { id: 67, theme: "厨房餐具", word: "microwave", cn: "微波炉", ex: "Heat the soup in the microwave." },
  { id: 68, theme: "厨房餐具", word: "oven", cn: "烤箱", ex: "Bake the cake in the oven." },
  { id: 69, theme: "厨房餐具", word: "stove", cn: "炉灶", ex: "She is cooking on the stove." },
  { id: 70, theme: "厨房餐具", word: "sink", cn: "水槽", ex: "Wash the dishes in the sink." },
  { id: 71, theme: "厨房餐具", word: "faucet", cn: "水龙头（英式 tap）", ex: "Turn off the faucet." },
  { id: 72, theme: "厨房餐具", word: "counter", cn: "操作台，柜台", ex: "Wipe the kitchen counter." },
  { id: 73, theme: "厨房餐具", word: "cabinet", cn: "橱柜", ex: "The cups are in the cabinet." },
  { id: 74, theme: "厨房餐具", word: "drawer", cn: "抽屉", ex: "Open the top drawer." },
  { id: 75, theme: "厨房餐具", word: "shelf", cn: "架子，搁板", ex: "Put the book on the shelf." },
  { id: 76, theme: "厨房餐具", word: "trash can", cn: "垃圾桶（英式 bin）", ex: "Throw it in the trash can." },
  { id: 77, theme: "厨房餐具", word: "pantry", cn: "食品储物柜", ex: "" },
  { id: 78, theme: "厨房餐具", word: "fork", cn: "叉子", ex: "Eat with a knife and fork." },
  { id: 79, theme: "厨房餐具", word: "knife", cn: "刀", ex: "Cut the bread with a knife." },
  { id: 80, theme: "厨房餐具", word: "spoon", cn: "勺子，匙", ex: "Stir the coffee with a spoon." },
  { id: 81, theme: "厨房餐具", word: "teaspoon", cn: "茶匙", ex: "Add a teaspoon of sugar." },
  { id: 82, theme: "厨房餐具", word: "chopsticks", cn: "筷子", ex: "She eats rice with chopsticks." },
  { id: 83, theme: "厨房餐具", word: "plate", cn: "盘子", ex: "Put the food on a plate." },
  { id: 84, theme: "厨房餐具", word: "bowl", cn: "碗", ex: "a bowl of soup" },
  { id: 85, theme: "厨房餐具", word: "mug", cn: "马克杯", ex: "a mug of hot coffee" },
  { id: 86, theme: "厨房餐具", word: "cup", cn: "杯子", ex: "a cup of tea" },
  { id: 87, theme: "厨房餐具", word: "teapot", cn: "茶壶", ex: "" },
  { id: 88, theme: "厨房餐具", word: "napkin", cn: "餐巾", ex: "Wipe your mouth with a napkin." },
  { id: 89, theme: "厨房餐具", word: "glass", cn: "玻璃杯", ex: "a glass of water" },
  { id: 90, theme: "厨房餐具", word: "jar", cn: "罐子", ex: "a jar of jam" },
  { id: 91, theme: "厨房餐具", word: "wineglass", cn: "葡萄酒杯", ex: "" },
  { id: 92, theme: "厨房餐具", word: "grater", cn: "擦丝器，礤床", ex: "" },
  { id: 93, theme: "厨房餐具", word: "peeler", cn: "削皮刀", ex: "Peel the potato with a peeler." },
  { id: 94, theme: "厨房餐具", word: "whisk", cn: "打蛋器", ex: "Beat the eggs with a whisk." },
  { id: 95, theme: "厨房餐具", word: "cutting board", cn: "案板，切菜板", ex: "Chop the onions on the cutting board." },
  { id: 96, theme: "厨房餐具", word: "scissors", cn: "剪刀", ex: "Cut the paper with scissors." },
  { id: 97, theme: "厨房餐具", word: "can opener", cn: "开罐器", ex: "Open the can with a can opener." },
  { id: 98, theme: "厨房餐具", word: "bottle opener", cn: "开瓶器", ex: "" },
  { id: 99, theme: "厨房餐具", word: "corkscrew", cn: "开酒器，瓶塞钻", ex: "" },
  { id: 100, theme: "厨房餐具", word: "wooden spoon", cn: "木勺", ex: "" },
  { id: 101, theme: "厨房餐具", word: "spatula", cn: "锅铲，刮铲", ex: "Flip the pancake with a spatula." },
  { id: 102, theme: "厨房餐具", word: "saucepan", cn: "长柄深底锅", ex: "" },
  { id: 103, theme: "厨房餐具", word: "frying pan", cn: "平底锅，煎锅", ex: "Fry the egg in a frying pan." },
  { id: 104, theme: "厨房餐具", word: "wok", cn: "炒锅", ex: "" },
  { id: 105, theme: "厨房餐具", word: "colander", cn: "滤盆，笊篱", ex: "Drain the pasta in a colander." },
  { id: 106, theme: "厨房餐具", word: "lid", cn: "盖子", ex: "Put the lid on the pot." },
  { id: 107, theme: "厨房餐具", word: "handle", cn: "把手，柄", ex: "Hold the handle carefully." },
  { id: 108, theme: "卧室", word: "coat hanger", cn: "衣架", ex: "Hang your coat on the hanger." },
  { id: 109, theme: "卧室", word: "alarm clock", cn: "闹钟", ex: "The alarm clock woke me up." },
  { id: 110, theme: "卧室", word: "pillow", cn: "枕头", ex: "I rested my head on the pillow." },
  { id: 111, theme: "卧室", word: "pillowcase", cn: "枕套", ex: "" },
  { id: 112, theme: "卧室", word: "wardrobe", cn: "衣柜", ex: "Hang the dress in the wardrobe." },
  { id: 113, theme: "卧室", word: "carpet", cn: "地毯", ex: "a soft carpet on the floor" },
  { id: 114, theme: "卧室", word: "nightstand", cn: "床头柜（英式 bedside table）", ex: "" },
  { id: 115, theme: "卧室", word: "duvet", cn: "羽绒被", ex: "" },
  { id: 116, theme: "卧室", word: "bed", cn: "床", ex: "Make your bed in the morning." },
  { id: 117, theme: "卧室", word: "quilt", cn: "被子", ex: "" },
  { id: 118, theme: "卧室", word: "blanket", cn: "毯子", ex: "She pulled the blanket over her shoulders." },
  { id: 119, theme: "卧室", word: "closet", cn: "壁橱，衣橱", ex: "Hang your coat in the closet." },
  { id: 120, theme: "卧室", word: "single bed", cn: "单人床", ex: "" },
  { id: 121, theme: "卧室", word: "double bed", cn: "双人床", ex: "" },
  { id: 122, theme: "浴室", word: "towel", cn: "毛巾", ex: "Dry yourself with a towel." },
  { id: 123, theme: "浴室", word: "toilet", cn: "马桶，厕所", ex: "Please flush the toilet." },
  { id: 124, theme: "浴室", word: "toilet paper", cn: "厕纸", ex: "We are out of toilet paper." },
  { id: 125, theme: "浴室", word: "soap", cn: "肥皂", ex: "Wash your hands with soap." },
  { id: 126, theme: "浴室", word: "sponge", cn: "海绵", ex: "" },
  { id: 127, theme: "浴室", word: "mirror", cn: "镜子", ex: "She looked at herself in the mirror." },
  { id: 128, theme: "浴室", word: "drain", cn: "下水道，排水口", ex: "The drain is blocked again." },
  { id: 129, theme: "浴室", word: "laundry basket", cn: "洗衣篮", ex: "Put the dirty clothes in the laundry basket." },
  { id: 130, theme: "浴室", word: "bathrobe", cn: "浴袍", ex: "" },
  { id: 131, theme: "浴室", word: "toothpaste", cn: "牙膏", ex: "Put some toothpaste on your brush." },
  { id: 132, theme: "浴室", word: "toothbrush", cn: "牙刷", ex: "" },
  { id: 133, theme: "浴室", word: "dental floss", cn: "牙线", ex: "" },
  { id: 134, theme: "浴室", word: "mouthwash", cn: "漱口水", ex: "" },
  { id: 135, theme: "浴室", word: "body lotion", cn: "身体乳", ex: "" },
  { id: 136, theme: "浴室", word: "face cream", cn: "面霜", ex: "" },
  { id: 137, theme: "工具", word: "wrench", cn: "扳手（英式 spanner）", ex: "Tighten the bolt with a wrench." },
  { id: 138, theme: "工具", word: "pliers", cn: "钳子", ex: "Grip the wire with pliers." },
  { id: 139, theme: "工具", word: "screwdriver", cn: "螺丝刀", ex: "Use a screwdriver to tighten the screw." },
  { id: 140, theme: "工具", word: "hammer", cn: "锤子", ex: "Hit the nail with a hammer." },
  { id: 141, theme: "工具", word: "toolbox", cn: "工具箱", ex: "" },
  { id: 142, theme: "工具", word: "drill bit", cn: "钻头", ex: "" },
  { id: 143, theme: "衣服鞋子", word: "shirt", cn: "衬衫", ex: "He ironed his shirt." },
  { id: 144, theme: "衣服鞋子", word: "T-shirt", cn: "T恤衫", ex: "a plain cotton T-shirt" },
  { id: 145, theme: "衣服鞋子", word: "blouse", cn: "女士衬衫", ex: "" },
  { id: 146, theme: "衣服鞋子", word: "sweater", cn: "毛衣", ex: "Put on a sweater, it is cold." },
  { id: 147, theme: "衣服鞋子", word: "cardigan", cn: "开襟毛衣", ex: "" },
  { id: 148, theme: "衣服鞋子", word: "jacket", cn: "夹克，短外套", ex: "a leather jacket" },
  { id: 149, theme: "衣服鞋子", word: "coat", cn: "外套，大衣", ex: "Put on your coat before you go out." },
  { id: 150, theme: "衣服鞋子", word: "dress", cn: "连衣裙", ex: "She bought a new dress." },
  { id: 151, theme: "衣服鞋子", word: "skirt", cn: "裙子", ex: "She wore a long skirt." },
  { id: 152, theme: "衣服鞋子", word: "jeans", cn: "牛仔裤", ex: "He wears jeans every day." },
  { id: 153, theme: "衣服鞋子", word: "trousers", cn: "裤子（美式 pants）", ex: "a pair of black trousers" },
  { id: 154, theme: "衣服鞋子", word: "shorts", cn: "短裤", ex: "I wear shorts in summer." },
  { id: 155, theme: "衣服鞋子", word: "tank top", cn: "背心", ex: "" },
  { id: 156, theme: "衣服鞋子", word: "leggings", cn: "紧身裤", ex: "" },
  { id: 157, theme: "衣服鞋子", word: "polo shirt", cn: "POLO衫，马球衫", ex: "" },
  { id: 158, theme: "衣服鞋子", word: "apron", cn: "围裙", ex: "She put on an apron to cook." },
  { id: 159, theme: "衣服鞋子", word: "uniform", cn: "制服", ex: "The children wear a school uniform." },
  { id: 160, theme: "衣服鞋子", word: "cotton", cn: "棉质的", ex: "a soft cotton shirt" },
  { id: 161, theme: "衣服鞋子", word: "leather", cn: "皮革的", ex: "a leather belt" },
  { id: 162, theme: "衣服鞋子", word: "silk", cn: "丝绸的", ex: "a silk scarf" },
  { id: 163, theme: "衣服鞋子", word: "wool", cn: "羊毛，羊毛的", ex: "a warm wool sweater" },
  { id: 164, theme: "衣服鞋子", word: "denim", cn: "牛仔布", ex: "a denim jacket" },
  { id: 165, theme: "衣服鞋子", word: "plain", cn: "素色的，纯色的", ex: "a plain white shirt" },
  { id: 166, theme: "衣服鞋子", word: "striped", cn: "条纹的", ex: "a striped shirt" },
  { id: 167, theme: "衣服鞋子", word: "checked", cn: "格子的", ex: "a checked shirt" },
  { id: 168, theme: "衣服鞋子", word: "tight", cn: "紧身的", ex: "These jeans are too tight." },
  { id: 169, theme: "衣服鞋子", word: "loose", cn: "宽松的", ex: "a loose, comfortable sweater" },
  { id: 170, theme: "衣服鞋子", word: "high heels", cn: "高跟鞋", ex: "She wore high heels to the party." },
  { id: 171, theme: "衣服鞋子", word: "flats", cn: "平底鞋", ex: "" },
  { id: 172, theme: "衣服鞋子", word: "flip-flops", cn: "人字拖", ex: "I wear flip-flops on the beach." },
  { id: 173, theme: "衣服鞋子", word: "sandals", cn: "凉鞋", ex: "" },
  { id: 174, theme: "衣服鞋子", word: "boots", cn: "靴子", ex: "warm winter boots" },
  { id: 175, theme: "衣服鞋子", word: "hiking boots", cn: "登山靴", ex: "" },
  { id: 176, theme: "衣服鞋子", word: "rain boots", cn: "雨靴", ex: "" },
  { id: 177, theme: "衣服鞋子", word: "lace", cn: "鞋带", ex: "Tie your shoe laces." },
  { id: 178, theme: "衣服鞋子", word: "sole", cn: "鞋底", ex: "" },
  { id: 179, theme: "衣服鞋子", word: "zipper", cn: "拉链（英式 zip）", ex: "Do up the zipper." },
  { id: 180, theme: "医疗健康", word: "doctor", cn: "医生", ex: "I need to see a doctor." },
  { id: 181, theme: "医疗健康", word: "nurse", cn: "护士", ex: "The nurse took my temperature." },
  { id: 182, theme: "医疗健康", word: "patient", cn: "病人", ex: "The patient waited to see the doctor." },
  { id: 183, theme: "医疗健康", word: "clinic", cn: "诊所", ex: "" },
  { id: 184, theme: "医疗健康", word: "hospital", cn: "医院", ex: "He was taken to the hospital." },
  { id: 185, theme: "医疗健康", word: "waiting room", cn: "候诊室", ex: "" },
  { id: 186, theme: "医疗健康", word: "appointment", cn: "预约", ex: "I made an appointment with the doctor." },
  { id: 187, theme: "医疗健康", word: "prescription", cn: "处方", ex: "The doctor wrote a prescription." },
  { id: 188, theme: "医疗健康", word: "medicine", cn: "药，药物", ex: "Take your medicine after meals." },
  { id: 189, theme: "医疗健康", word: "pills", cn: "药丸", ex: "" },
  { id: 190, theme: "医疗健康", word: "tablet", cn: "药片", ex: "Take one tablet a day." },
  { id: 191, theme: "医疗健康", word: "capsule", cn: "胶囊", ex: "" },
  { id: 192, theme: "医疗健康", word: "thermometer", cn: "温度计", ex: "" },
  { id: 193, theme: "医疗健康", word: "face mask", cn: "口罩", ex: "Please wear a face mask." },
  { id: 194, theme: "医疗健康", word: "blood pressure", cn: "血压", ex: "The nurse checked my blood pressure." },
  { id: 195, theme: "医疗健康", word: "blood test", cn: "血检", ex: "" },
  { id: 196, theme: "医疗健康", word: "vaccination", cn: "接种疫苗", ex: "" },
  { id: 197, theme: "医疗健康", word: "syringe", cn: "注射器", ex: "" },
  { id: 198, theme: "医疗健康", word: "needle", cn: "针头", ex: "" },
  { id: 199, theme: "医疗健康", word: "ambulance", cn: "救护车", ex: "Call an ambulance!" },
  { id: 200, theme: "医疗健康", word: "surgeon", cn: "外科医生", ex: "" },
  { id: 201, theme: "医疗健康", word: "wheelchair", cn: "轮椅", ex: "" },
  { id: 202, theme: "医疗健康", word: "X-ray", cn: "X光片", ex: "" },
  { id: 203, theme: "医疗健康", word: "stretcher", cn: "担架", ex: "" },
  { id: 204, theme: "医疗健康", word: "painkiller", cn: "止痛药", ex: "Take a painkiller for the headache." },
  { id: 205, theme: "医疗健康", word: "pharmacist", cn: "药剂师", ex: "" },
  { id: 206, theme: "医疗健康", word: "antibiotics", cn: "抗生素", ex: "" },
  { id: 207, theme: "医疗健康", word: "vitamins", cn: "维生素", ex: "" },
  { id: 208, theme: "医疗健康", word: "cough medicine", cn: "止咳药", ex: "" },
  { id: 209, theme: "医疗健康", word: "sleeping pills", cn: "安眠药", ex: "" },
  { id: 210, theme: "医疗健康", word: "first-aid kit", cn: "急救箱", ex: "" },
  { id: 211, theme: "医疗健康", word: "side effects", cn: "副作用", ex: "" },
  { id: 212, theme: "医疗健康", word: "dosage", cn: "剂量，用量", ex: "" },
  { id: 213, theme: "城镇购物", word: "customer", cn: "顾客", ex: "The customer paid at the checkout." },
  { id: 214, theme: "城镇购物", word: "receipt", cn: "收据", ex: "Keep your receipt." },
  { id: 215, theme: "城镇购物", word: "cashier", cn: "收银员", ex: "" },
  { id: 216, theme: "城镇购物", word: "cash register", cn: "收银机", ex: "" },
  { id: 217, theme: "城镇购物", word: "checkout", cn: "结账，收银台", ex: "" },
  { id: 218, theme: "城镇购物", word: "self checkout", cn: "自助结账", ex: "" },
  { id: 219, theme: "城镇购物", word: "shopping cart", cn: "购物车（英式 trolley）", ex: "" },
  { id: 220, theme: "城镇购物", word: "basket", cn: "购物篮", ex: "" },
  { id: 221, theme: "城镇购物", word: "shopping bag", cn: "购物袋", ex: "" },
  { id: 222, theme: "城镇购物", word: "barcode", cn: "条形码", ex: "" },
  { id: 223, theme: "城镇购物", word: "coupon", cn: "优惠券", ex: "" },
  { id: 224, theme: "城镇购物", word: "special offer", cn: "特价优惠", ex: "" },
  { id: 225, theme: "城镇购物", word: "bargain", cn: "便宜货，划算的东西", ex: "It was a real bargain." },
  { id: 226, theme: "城镇购物", word: "line", cn: "排队（英式 queue）", ex: "Please wait in line." },
  { id: 227, theme: "城镇购物", word: "open", cn: "营业的，开门的", ex: "The shop is open until 9 pm." },
  { id: 228, theme: "城镇购物", word: "closed", cn: "停业的，关门的", ex: "The shop is closed on Sundays." },
  { id: 229, theme: "城镇购物", word: "online shopping", cn: "网上购物", ex: "" },
  { id: 230, theme: "城镇购物", word: "market", cn: "市场", ex: "We buy vegetables at the market." },
  { id: 231, theme: "城镇购物", word: "bakery", cn: "面包房", ex: "" },
  { id: 232, theme: "城镇购物", word: "butcher", cn: "肉店", ex: "" },
  { id: 233, theme: "城镇购物", word: "grocery store", cn: "食品杂货店", ex: "" },
  { id: 234, theme: "城镇购物", word: "café", cn: "咖啡馆", ex: "Let's meet at the café." },
  { id: 235, theme: "城镇购物", word: "bookstore", cn: "书店", ex: "" },
  { id: 236, theme: "城镇购物", word: "pet store", cn: "宠物店", ex: "" },
  { id: 237, theme: "城镇购物", word: "toy store", cn: "玩具店", ex: "" },
  { id: 238, theme: "城镇购物", word: "shoe store", cn: "鞋店", ex: "" },
  { id: 239, theme: "城镇购物", word: "hardware store", cn: "五金店", ex: "" },
  { id: 240, theme: "城镇购物", word: "electronics store", cn: "电子产品店", ex: "" },
  { id: 241, theme: "城镇购物", word: "optician", cn: "眼镜店", ex: "" },
  { id: 242, theme: "城镇购物", word: "travel agent", cn: "旅行社", ex: "" },
  { id: 243, theme: "城镇购物", word: "gift shop", cn: "礼品店", ex: "" },
  { id: 244, theme: "蔬菜", word: "onion", cn: "洋葱", ex: "Chop the onion finely." },
  { id: 245, theme: "蔬菜", word: "carrot", cn: "胡萝卜", ex: "Rabbits love carrots." },
  { id: 246, theme: "蔬菜", word: "garlic", cn: "大蒜", ex: "Add a clove of garlic." },
  { id: 247, theme: "蔬菜", word: "tomato", cn: "番茄，西红柿", ex: "a ripe red tomato" },
  { id: 248, theme: "蔬菜", word: "potato", cn: "土豆，马铃薯", ex: "mashed potato" },
  { id: 249, theme: "蔬菜", word: "cucumber", cn: "黄瓜", ex: "" },
  { id: 250, theme: "蔬菜", word: "lettuce", cn: "生菜", ex: "" },
  { id: 251, theme: "蔬菜", word: "cabbage", cn: "卷心菜", ex: "" },
  { id: 252, theme: "蔬菜", word: "spinach", cn: "菠菜", ex: "" },
  { id: 253, theme: "蔬菜", word: "broccoli", cn: "西兰花", ex: "" },
  { id: 254, theme: "蔬菜", word: "celery", cn: "芹菜", ex: "" },
  { id: 255, theme: "蔬菜", word: "peas", cn: "豌豆", ex: "a handful of green peas" },
  { id: 256, theme: "蔬菜", word: "green beans", cn: "四季豆", ex: "" },
  { id: 257, theme: "蔬菜", word: "corn", cn: "玉米（英式 sweetcorn）", ex: "" },
  { id: 258, theme: "蔬菜", word: "bean sprouts", cn: "豆芽", ex: "" },
  { id: 259, theme: "蔬菜", word: "mushroom", cn: "蘑菇", ex: "" },
  { id: 260, theme: "蔬菜", word: "pumpkin", cn: "南瓜", ex: "" },
  { id: 261, theme: "蔬菜", word: "asparagus", cn: "芦笋", ex: "" },
  { id: 262, theme: "蔬菜", word: "chili", cn: "辣椒", ex: "" },
  { id: 263, theme: "蔬菜", word: "radish", cn: "小萝卜", ex: "" },
  { id: 264, theme: "蔬菜", word: "spring onion", cn: "葱", ex: "" },
  { id: 265, theme: "蔬菜", word: "salad", cn: "沙拉", ex: "a fresh green salad" },
  { id: 266, theme: "蔬菜", word: "fresh", cn: "新鲜的", ex: "fresh vegetables" },
  { id: 267, theme: "蔬菜", word: "frozen", cn: "冷冻的", ex: "frozen peas" },
  { id: 268, theme: "蔬菜", word: "organic", cn: "有机的", ex: "organic vegetables" },
  { id: 269, theme: "蔬菜", word: "raw", cn: "生的，未煮的", ex: "raw carrots" },
  { id: 270, theme: "水果", word: "apple", cn: "苹果", ex: "An apple a day keeps the doctor away." },
  { id: 271, theme: "水果", word: "banana", cn: "香蕉", ex: "" },
  { id: 272, theme: "水果", word: "orange", cn: "橙子", ex: "" },
  { id: 273, theme: "水果", word: "pear", cn: "梨", ex: "" },
  { id: 274, theme: "水果", word: "grapes", cn: "葡萄", ex: "a bunch of grapes" },
  { id: 275, theme: "水果", word: "watermelon", cn: "西瓜", ex: "a slice of watermelon" },
  { id: 276, theme: "水果", word: "lemon", cn: "柠檬", ex: "" },
  { id: 277, theme: "水果", word: "lime", cn: "酸橙，青柠", ex: "" },
  { id: 278, theme: "水果", word: "grapefruit", cn: "葡萄柚", ex: "" },
  { id: 279, theme: "水果", word: "strawberry", cn: "草莓", ex: "" },
  { id: 280, theme: "水果", word: "blueberry", cn: "蓝莓", ex: "" },
  { id: 281, theme: "水果", word: "raspberry", cn: "覆盆子，树莓", ex: "" },
  { id: 282, theme: "水果", word: "blackberry", cn: "黑莓", ex: "" },
  { id: 283, theme: "水果", word: "cranberry", cn: "蔓越莓", ex: "" },
  { id: 284, theme: "水果", word: "peach", cn: "桃子", ex: "" },
  { id: 285, theme: "水果", word: "mango", cn: "芒果", ex: "" },
  { id: 286, theme: "水果", word: "plum", cn: "李子", ex: "" },
  { id: 287, theme: "水果", word: "cherry", cn: "樱桃", ex: "" },
  { id: 288, theme: "水果", word: "apricot", cn: "杏", ex: "" },
  { id: 289, theme: "水果", word: "lychee", cn: "荔枝", ex: "" },
  { id: 290, theme: "水果", word: "coconut", cn: "椰子", ex: "" },
  { id: 291, theme: "水果", word: "ripe", cn: "成熟的", ex: "The bananas are ripe now." },
  { id: 292, theme: "水果", word: "sweet", cn: "甜的", ex: "sweet, juicy strawberries" },
  { id: 293, theme: "水果", word: "sour", cn: "酸的", ex: "The lemon tastes sour." },
  { id: 294, theme: "咖啡厅", word: "coffee", cn: "咖啡", ex: "a cup of hot coffee" },
  { id: 295, theme: "咖啡厅", word: "espresso", cn: "浓缩咖啡", ex: "" },
  { id: 296, theme: "咖啡厅", word: "cappuccino", cn: "卡布奇诺", ex: "" },
  { id: 297, theme: "咖啡厅", word: "iced coffee", cn: "冰咖啡", ex: "" },
  { id: 298, theme: "咖啡厅", word: "tea", cn: "茶", ex: "a pot of green tea" },
  { id: 299, theme: "咖啡厅", word: "milk", cn: "牛奶", ex: "a glass of milk" },
  { id: 300, theme: "咖啡厅", word: "waiter", cn: "服务员", ex: "The waiter took our order." },
  { id: 301, theme: "咖啡厅", word: "waitress", cn: "女服务员", ex: "" },
  { id: 302, theme: "咖啡厅", word: "to serve", cn: "上餐，端上", ex: "The café serves breakfast all day." },
  { id: 303, theme: "咖啡厅", word: "orange juice", cn: "橙汁", ex: "a fresh orange juice" },
  { id: 304, theme: "咖啡厅", word: "apple juice", cn: "苹果汁", ex: "" },
  { id: 305, theme: "咖啡厅", word: "juice", cn: "果汁", ex: "freshly squeezed juice" },
  { id: 306, theme: "咖啡厅", word: "smoothie", cn: "果昔，思慕雪", ex: "a strawberry smoothie" },
  { id: 307, theme: "咖啡厅", word: "milkshake", cn: "奶昔", ex: "a chocolate milkshake" },
  { id: 308, theme: "早餐", word: "breakfast", cn: "早餐", ex: "I have breakfast at seven." },
  { id: 309, theme: "早餐", word: "cereal", cn: "麦片", ex: "I eat cereal every morning." },
  { id: 310, theme: "早餐", word: "toast", cn: "吐司，烤面包片", ex: "buttered toast" },
  { id: 311, theme: "早餐", word: "croissant", cn: "牛角面包", ex: "" },
  { id: 312, theme: "早餐", word: "omelet", cn: "煎蛋卷", ex: "a cheese omelet" },
  { id: 313, theme: "早餐", word: "bagel", cn: "贝果", ex: "" },
  { id: 314, theme: "早餐", word: "sandwich", cn: "三明治", ex: "a ham sandwich" },
  { id: 315, theme: "早餐", word: "cheese", cn: "奶酪，芝士", ex: "a slice of cheese" },
  { id: 316, theme: "早餐", word: "ham", cn: "火腿", ex: "ham and eggs" },
  { id: 317, theme: "早餐", word: "jam", cn: "果酱", ex: "strawberry jam on toast" },
  { id: 318, theme: "早餐", word: "marmalade", cn: "橘子果酱", ex: "" },
  { id: 319, theme: "早餐", word: "honey", cn: "蜂蜜", ex: "honey on warm toast" },
  { id: 320, theme: "早餐", word: "French toast", cn: "法式吐司", ex: "" },
  { id: 321, theme: "早餐", word: "avocado toast", cn: "牛油果吐司", ex: "" },
];
