// GRE 核心词库 · 200词
// tier 1: 必掌握 100词 | tier 2: 高频 100词

export const GRE_VOCAB = [

  // ══════════════════════════════
  // TIER 1 · 必掌握（100词）
  // ══════════════════════════════

  { id: 0,   tier: 1, word: "aberrant",     phon: "/æˈbɛrənt/",      cn: "异常的，偏离常规的",       root: "ab-（偏离）+ err（游走）",         ex: "The scientist dismissed the aberrant result as a measurement artifact." },
  { id: 1,   tier: 1, word: "abscond",      phon: "/æbˈskɒnd/",      cn: "潜逃，秘密逃走",           root: "abs-（离开）+ cond（藏匿）",        ex: "The treasurer absconded with the company's funds overnight." },
  { id: 2,   tier: 1, word: "abstemious",   phon: "/æbˈstiːmiəs/",   cn: "节制的，有节制饮食的",     root: "abs-（远离）+ teme（喝酒）",        ex: "He led an abstemious life, eating sparingly and never drinking alcohol." },
  { id: 3,   tier: 1, word: "acumen",       phon: "/ˈækjumən/",      cn: "敏锐，洞察力",             root: "acu-（尖锐）→ 思维尖锐",           ex: "Her financial acumen allowed the startup to survive its first year." },
  { id: 4,   tier: 1, word: "admonish",     phon: "/ədˈmɒnɪʃ/",     cn: "警告，告诫",               root: "ad-（向）+ mon（警告）",            ex: "The professor admonished students who failed to cite their sources." },
  { id: 5,   tier: 1, word: "alacrity",     phon: "/əˈlækrɪti/",     cn: "欣然，敏捷，乐意",         root: "alacer（活泼的）→ 积极响应",        ex: "She accepted the research offer with alacrity." },
  { id: 6,   tier: 1, word: "alleviate",    phon: "/əˈliːvieɪt/",    cn: "减轻，缓解",               root: "al- + lev（轻）→ 使变轻",           ex: "The new drug significantly alleviated chronic pain in trial participants." },
  { id: 7,   tier: 1, word: "ameliorate",   phon: "/əˈmiːliəreɪt/",  cn: "改善，改良",               root: "melior（更好的）→ 使变好",          ex: "Policy reforms were introduced to ameliorate poverty in urban areas." },
  { id: 8,   tier: 1, word: "anomalous",    phon: "/əˈnɒmələs/",     cn: "异常的，不规则的",         root: "an-（不）+ homos（相同）",          ex: "Anomalous readings led researchers to question their initial hypothesis." },
  { id: 9,   tier: 1, word: "antipathy",    phon: "/ænˈtɪpəθi/",     cn: "强烈反感，厌恶",           root: "anti-（反）+ path（感情）",         ex: "His antipathy toward bureaucracy was evident throughout his writings." },
  { id: 10,  tier: 1, word: "apathy",       phon: "/ˈæpəθi/",        cn: "冷漠，缺乏兴趣",           root: "a-（无）+ path（感情）",            ex: "Voter apathy contributed to the historically low turnout in the election." },
  { id: 11,  tier: 1, word: "arcane",       phon: "/ɑːrˈkeɪn/",      cn: "神秘的，晦涩难懂的",       root: "arca（箱子）→ 藏起来的知识",        ex: "The professor specialized in the arcane mathematical structures." },
  { id: 12,  tier: 1, word: "arduous",      phon: "/ˈɑːrdjuəs/",     cn: "艰巨的，费力的",           root: "ardus（陡峭的）→ 攀爬很费力",       ex: "The arduous climb up the research ladder discouraged many students." },
  { id: 13,  tier: 1, word: "ascetic",      phon: "/əˈsɛtɪk/",       cn: "苦行的，禁欲的；苦行者",   root: "askein（锻炼）→ 自律修行",          ex: "The philosopher led an ascetic life, forgoing material comforts." },
  { id: 14,  tier: 1, word: "assuage",      phon: "/əˈsweɪdʒ/",      cn: "减轻，缓和，满足（需求）", root: "ad- + suavis（甜）→ 使变甜蜜",      ex: "Nothing could assuage her grief following the loss of the grant." },
  { id: 15,  tier: 1, word: "attenuate",    phon: "/əˈtɛnjueɪt/",    cn: "减弱，使变细，稀释",       root: "ad- + tenuis（细）→ 使变薄",        ex: "The atmosphere attenuates solar radiation before it reaches the surface." },
  { id: 16,  tier: 1, word: "audacious",    phon: "/ɔːˈdeɪʃəs/",     cn: "大胆的，鲁莽的",           root: "audax（勇敢的）→ 胆大妄为",         ex: "The team proposed an audacious plan to sequence the entire human proteome." },
  { id: 17,  tier: 1, word: "auspicious",   phon: "/ɔːˈspɪʃəs/",     cn: "吉祥的，有利的",           root: "auspex（占卜师）→ 预兆好",          ex: "The record funding round was an auspicious start for the lab." },
  { id: 18,  tier: 1, word: "avarice",      phon: "/ˈævərɪs/",        cn: "贪婪，贪财",               root: "avere（渴望）→ 贪得无厌",           ex: "His avarice blinded him to the ethical implications of his research." },
  { id: 19,  tier: 1, word: "banal",        phon: "/bəˈnɑːl/",        cn: "平庸的，老生常谈的",       root: "ban（公共的）→ 人人皆知→ 陈腐",    ex: "Critics dismissed the paper as banal, offering no original insight." },
  { id: 20,  tier: 1, word: "belie",        phon: "/bɪˈlaɪ/",         cn: "掩盖，与…矛盾，使失望",   root: "be- + lie（谎言）→ 制造假象",        ex: "Her calm expression belied the anxiety she felt before the defense." },
  { id: 21,  tier: 1, word: "bombastic",    phon: "/bɒmˈbæstɪk/",    cn: "夸大的，言过其实的",       root: "bombax（棉花）→ 填充物→ 虚话连篇", ex: "His bombastic rhetoric failed to mask the weakness of his argument." },
  { id: 22,  tier: 1, word: "capricious",   phon: "/kəˈprɪʃəs/",     cn: "变化无常的，任性的",       root: "capro（山羊）→ 山羊乱跳→ 反复无常", ex: "The capricious nature of the funding committee frustrated researchers." },
  { id: 23,  tier: 1, word: "castigate",    phon: "/ˈkæstɪɡeɪt/",    cn: "严厉批评，惩罚",           root: "castus（纯洁）→ 纠正使纯洁",        ex: "The review board castigated the lab for its lax data-management practices." },
  { id: 24,  tier: 1, word: "caustic",      phon: "/ˈkɔːstɪk/",       cn: "刻薄的，腐蚀性的",         root: "kaiein（燃烧）→ 灼烧性的",          ex: "Her caustic wit alienated colleagues during seminars." },
  { id: 25,  tier: 1, word: "chicanery",    phon: "/ʃɪˈkeɪnəri/",     cn: "欺骗，狡辩",               root: "chicaner（诡辩）→ 耍手段",          ex: "The investigation revealed chicanery in the clinical trial data." },
  { id: 26,  tier: 1, word: "circumspect",  phon: "/ˈsɜːrkəmspɛkt/", cn: "谨慎的，慎重的",           root: "circum-（周围）+ spect（看）→ 四处张望", ex: "A circumspect approach to the experiment prevented costly errors." },
  { id: 27,  tier: 1, word: "clandestine",  phon: "/klænˈdɛstɪn/",   cn: "秘密的，暗中进行的",       root: "clam（秘密地）→ 隐秘行事",          ex: "The clandestine data-sharing arrangement violated ethics guidelines." },
  { id: 28,  tier: 1, word: "cogent",       phon: "/ˈkoʊdʒənt/",      cn: "令人信服的，有力的",       root: "co-（一起）+ agere（驱动）→ 论点有力", ex: "She presented a cogent argument for expanding the study's sample size." },
  { id: 29,  tier: 1, word: "commensurate", phon: "/kəˈmɛnʃərɪt/",   cn: "相称的，相当的",           root: "com-（共同）+ mensura（测量）",      ex: "The salary was commensurate with her level of expertise." },
  { id: 30,  tier: 1, word: "confound",     phon: "/kənˈfaʊnd/",      cn: "使困惑，混淆，证伪",       root: "con- + fundere（倒）→ 混在一起",    ex: "Confounding variables made it difficult to isolate the treatment effect." },
  { id: 31,  tier: 1, word: "convoluted",   phon: "/ˈkɒnvəluːtɪd/",  cn: "复杂的，难懂的",           root: "con- + volvere（卷）→ 卷在一起",    ex: "The convoluted methodology section confused even experienced reviewers." },
  { id: 32,  tier: 1, word: "copious",      phon: "/ˈkoʊpiəs/",       cn: "大量的，丰富的",           root: "copia（丰富）→ 大量存在",            ex: "She took copious notes during the keynote lecture." },
  { id: 33,  tier: 1, word: "decry",        phon: "/dɪˈkraɪ/",        cn: "公开批评，谴责",           root: "de-（向下）+ crier（叫喊）→ 喊着贬低", ex: "Critics decried the study for its biased sampling procedures." },
  { id: 34,  tier: 1, word: "deferential",  phon: "/ˌdɛfəˈrɛnʃəl/",  cn: "顺从的，恭敬的",           root: "de- + ferre（带）→ 将意见让给别人",  ex: "Junior researchers were overly deferential to the lab director's opinions." },
  { id: 35,  tier: 1, word: "deride",       phon: "/dɪˈraɪd/",        cn: "嘲笑，嘲弄",               root: "de-（向下）+ ridere（笑）→ 嘲笑",   ex: "Colleagues derided the hypothesis until replication confirmed it." },
  { id: 36,  tier: 1, word: "desultory",    phon: "/ˈdɛsəltɔːri/",   cn: "散漫的，无计划的",         root: "de- + salire（跳）→ 东跳西跳",       ex: "His desultory approach to literature review left significant gaps." },
  { id: 37,  tier: 1, word: "didactic",     phon: "/daɪˈdæktɪk/",     cn: "教诲的，说教的",           root: "didaskein（教导）→ 以教为目的",      ex: "The essay's didactic tone undermined its scholarly credibility." },
  { id: 38,  tier: 1, word: "diffident",    phon: "/ˈdɪfɪdənt/",      cn: "缺乏自信的，羞怯的",       root: "dis- + fidere（信任）→ 不信任自己",  ex: "Despite her brilliance, she remained diffident in academic discussions." },
  { id: 39,  tier: 1, word: "discern",      phon: "/dɪˈsɜːrn/",       cn: "辨别，看出，觉察",         root: "dis-（分开）+ cernere（筛选）",      ex: "A trained reader can discern the author's underlying assumptions." },
  { id: 40,  tier: 1, word: "dissonance",   phon: "/ˈdɪsənəns/",      cn: "不和谐，矛盾，认知失调",   root: "dis-（分离）+ sonus（声音）",        ex: "Cognitive dissonance arose when new data contradicted their model." },
  { id: 41,  tier: 1, word: "dogmatic",     phon: "/dɒɡˈmætɪk/",      cn: "教条的，武断的",           root: "dogma（教义）→ 不容置疑的信条",     ex: "A dogmatic adherence to one theory blocked progress in the field." },
  { id: 42,  tier: 1, word: "ebullient",    phon: "/ɪˈbʌliənt/",      cn: "热情洋溢的，充满活力的",   root: "e- + bullire（沸腾）→ 热情沸腾",    ex: "Her ebullient personality made her a natural leader of the team." },
  { id: 43,  tier: 1, word: "efficacy",     phon: "/ˈɛfɪkəsi/",       cn: "功效，有效性",             root: "efficere（完成）→ 达成效果的能力",   ex: "Phase III trials confirmed the drug's efficacy in reducing tumor size." },
  { id: 44,  tier: 1, word: "egregious",    phon: "/ɪˈɡriːdʒəs/",     cn: "极坏的，令人震惊的",       root: "e-（出）+ grex（群体）→ 从人群中突出（因太差）", ex: "The paper contained egregious errors in its statistical analysis." },
  { id: 45,  tier: 1, word: "elusive",      phon: "/ɪˈluːsɪv/",       cn: "难以捉摸的，逃避的",       root: "e-（出）+ ludere（玩）→ 溜掉了",    ex: "A unified theory of consciousness remains elusive." },
  { id: 46,  tier: 1, word: "empirical",    phon: "/ɪmˈpɪrɪkəl/",     cn: "以实验为依据的，经验主义的", root: "empeiria（经验）→ 基于观察",         ex: "The claim lacked empirical support and was dismissed by reviewers." },
  { id: 47,  tier: 1, word: "ephemeral",    phon: "/ɪˈfɛmərəl/",      cn: "短暂的，转瞬即逝的",       root: "epi-（在…上）+ hemera（天）→ 只活一天", ex: "Social media trends are often ephemeral, fading within days." },
  { id: 48,  tier: 1, word: "equivocal",    phon: "/ɪˈkwɪvəkəl/",     cn: "模糊的，含糊其辞的",       root: "equi-（相等）+ vox（声音）→ 两可之词", ex: "The results were equivocal, warranting further investigation." },
  { id: 49,  tier: 1, word: "erudite",      phon: "/ˈɛruːdaɪt/",      cn: "博学的，有学问的",         root: "e-（出）+ rudis（粗糙）→ 去掉粗糙",  ex: "The erudite professor could lecture fluently across three disciplines." },
  { id: 50,  tier: 1, word: "esoteric",     phon: "/ˌɛsəˈtɛrɪk/",     cn: "深奥的，只有内行才懂的",   root: "esotero（内部的）→ 内部人才知道",    ex: "The paper's esoteric notation alienated a broader audience." },
  { id: 51,  tier: 1, word: "exacerbate",   phon: "/ɪɡˈzæsərbeɪt/",  cn: "加剧，使恶化",             root: "ex- + acerbus（苦涩）→ 使更苦",     ex: "Poor ventilation exacerbated the spread of the airborne pathogen." },
  { id: 52,  tier: 1, word: "exonerate",    phon: "/ɪɡˈzɒnəreɪt/",   cn: "宣告无罪，免除责任",       root: "ex-（去除）+ onus（负担）→ 卸去重担", ex: "New forensic evidence exonerated the researcher of all misconduct charges." },
  { id: 53,  tier: 1, word: "extol",        phon: "/ɪkˈstoʊl/",       cn: "高度赞扬，颂扬",           root: "ex-（向上）+ tollere（举起）→ 高举颂扬", ex: "The review committee extolled the study's innovative methodology." },
  { id: 54,  tier: 1, word: "fallacious",   phon: "/fəˈleɪʃəs/",      cn: "错误的，谬误的",           root: "fallax（欺骗性的）→ 含有谬误",       ex: "The editorial exposed the fallacious reasoning in the popular article." },
  { id: 55,  tier: 1, word: "fastidious",   phon: "/fæˈstɪdiəs/",     cn: "一丝不苟的，挑剔的",       root: "fastidium（厌恶）→ 对不完美极度挑剔", ex: "Her fastidious attention to protocol ensured reproducible results." },
  { id: 56,  tier: 1, word: "fervent",      phon: "/ˈfɜːrvənt/",      cn: "热情的，热烈的",           root: "fervere（沸腾）→ 热情如沸",          ex: "He was a fervent advocate for open-access scientific publishing." },
  { id: 57,  tier: 1, word: "flagrant",     phon: "/ˈfleɪɡrənt/",     cn: "公然的，罪不可赦的",       root: "flagrare（燃烧）→ 显而易见的恶行",   ex: "The plagiarism was so flagrant that retraction was immediate." },
  { id: 58,  tier: 1, word: "florid",       phon: "/ˈflɒrɪd/",        cn: "华丽的，过分装饰的；红润的", root: "flos（花）→ 像花一样过度装饰",        ex: "His florid prose obscured rather than illuminated his argument." },
  { id: 59,  tier: 1, word: "fortuitous",   phon: "/fɔːrˈtjuːɪtəs/",  cn: "偶然的，幸运的",           root: "fortuna（运气）→ 碰运气",            ex: "A fortuitous equipment malfunction led to an unexpected discovery." },
  { id: 60,  tier: 1, word: "furtive",      phon: "/ˈfɜːrtɪv/",       cn: "偷偷摸摸的，鬼鬼祟祟的",  root: "furtum（偷窃）→ 像小偷一样",         ex: "The researchers made furtive glances at a competitor's poster." },
  { id: 61,  tier: 1, word: "garrulous",    phon: "/ˈɡærələs/",        cn: "喋喋不休的，话多的",       root: "garrire（喋喋不休）→ 话太多",        ex: "The garrulous reviewer buried his key criticisms in lengthy prose." },
  { id: 62,  tier: 1, word: "glib",         phon: "/ɡlɪb/",            cn: "油嘴滑舌的，不诚恳的",     root: "glib（荷兰语：光滑）→ 话说得太顺溜", ex: "His glib response to the criticism failed to address the core issue." },
  { id: 63,  tier: 1, word: "gregarious",   phon: "/ɡrɪˈɡɛəriəs/",    cn: "爱交际的，群居的",         root: "grex（群体）→ 喜欢聚在一起",         ex: "Her gregarious nature helped her build a wide professional network." },
  { id: 64,  tier: 1, word: "guile",        phon: "/ɡaɪl/",            cn: "狡猾，欺骗，诡计",         root: "wile（诡计）→ 狡猾策略",             ex: "He used guile rather than force to secure grant funding." },
  { id: 65,  tier: 1, word: "hackneyed",    phon: "/ˈhæknid/",         cn: "陈腐的，老套的",           root: "hackney（供出租的马）→ 反复使用→ 陈旧", ex: "The metaphor was so hackneyed that the editor struck it immediately." },
  { id: 66,  tier: 1, word: "harbinger",    phon: "/ˈhɑːrbɪndʒər/",   cn: "预兆，先驱",               root: "here（军队）+ berg（住所）→ 先驱部队", ex: "Early neural correlates may be harbingers of cognitive decline." },
  { id: 67,  tier: 1, word: "haughty",      phon: "/ˈhɔːti/",          cn: "傲慢的，自大的",           root: "haut（法语：高）→ 高高在上",          ex: "His haughty dismissal of junior colleagues damaged lab morale." },
  { id: 68,  tier: 1, word: "hegemony",     phon: "/hɪˈɡɛməni/",       cn: "霸权，主导地位",           root: "hegemon（领袖）→ 主导权",            ex: "The lab's hegemony in the field began to erode as competitors emerged." },
  { id: 69,  tier: 1, word: "hubris",       phon: "/ˈhjuːbrɪs/",       cn: "狂妄自大，傲慢",           root: "希腊语 hybris（傲慢）→ 过度自信",    ex: "His hubris in dismissing peer review led to a retracted paper." },
  { id: 70,  tier: 1, word: "iconoclast",   phon: "/aɪˈkɒnəklæst/",   cn: "打破传统者，批判偶像者",   root: "icon（图像）+ klast（打碎）→ 砸偶像",  ex: "The iconoclast researcher challenged decades of accepted theory." },
  { id: 71,  tier: 1, word: "ignominious",  phon: "/ˌɪɡnəˈmɪniəs/",   cn: "可耻的，丢脸的",           root: "in-（无）+ nomen（名声）→ 名誉扫地", ex: "The ignominious retraction tarnished the entire department." },
  { id: 72,  tier: 1, word: "impartial",    phon: "/ɪmˈpɑːrʃəl/",     cn: "公正的，不偏不倚的",       root: "im-（不）+ partial（偏向一方）",      ex: "An impartial meta-analysis synthesized conflicting study findings." },
  { id: 73,  tier: 1, word: "impetuous",    phon: "/ɪmˈpɛtʃuəs/",     cn: "冲动的，鲁莽的",           root: "impetus（冲力）→ 被冲动驱使",         ex: "His impetuous decision to submit before finalizing data proved costly." },
  { id: 74,  tier: 1, word: "implacable",   phon: "/ɪmˈplækəbəl/",    cn: "无法平息的，无情的",       root: "im-（不）+ placare（安抚）→ 无法安抚", ex: "The committee showed implacable opposition to the revised proposal." },
  { id: 75,  tier: 1, word: "incisive",     phon: "/ɪnˈsaɪsɪv/",      cn: "深刻的，一针见血的",       root: "incidere（切入）→ 切中要害",          ex: "Her incisive critique identified the study's fundamental flaw." },
  { id: 76,  tier: 1, word: "incongruous",  phon: "/ɪnˈkɒŋɡruəs/",    cn: "不协调的，不相称的",       root: "in-（不）+ congruere（符合）",        ex: "The casual tone was incongruous with the gravity of the findings." },
  { id: 77,  tier: 1, word: "indolent",     phon: "/ˈɪndələnt/",       cn: "懒惰的，懒散的",           root: "in-（不）+ dolere（痛苦）→ 不愿受苦", ex: "An indolent approach to data validation resulted in undetected errors." },
  { id: 78,  tier: 1, word: "ingenuous",    phon: "/ɪnˈdʒɛnjuəs/",     cn: "天真的，直率的，坦白的",   root: "in-（在内）+ genu（出生）→ 天生坦白", ex: "Her ingenuous admission of the study's limitations impressed the committee." },
  { id: 79,  tier: 1, word: "innocuous",    phon: "/ɪˈnɒkjuəs/",       cn: "无害的，不冒犯人的",       root: "in-（无）+ nocere（伤害）→ 不伤害",   ex: "The seemingly innocuous gene variant had profound phenotypic effects." },
  { id: 80,  tier: 1, word: "insipid",      phon: "/ɪnˈsɪpɪd/",        cn: "枯燥无味的，平淡的",       root: "in-（无）+ sapere（味道）→ 没味道",   ex: "The insipid presentation failed to engage the conference audience." },
  { id: 81,  tier: 1, word: "intractable",  phon: "/ɪnˈtræktəbəl/",   cn: "棘手的，难处理的",         root: "in-（不）+ tractare（拉）→ 拉不动",   ex: "Antibiotic resistance remains an intractable public health problem." },
  { id: 82,  tier: 1, word: "intrepid",     phon: "/ɪnˈtrɛpɪd/",       cn: "无畏的，勇敢的",           root: "in-（不）+ trepidus（恐惧）→ 毫不畏惧", ex: "The intrepid field researcher collected samples in extreme conditions." },
  { id: 83,  tier: 1, word: "irascible",    phon: "/ɪˈræsɪbəl/",       cn: "易怒的，性急的",           root: "ira（愤怒）→ 容易发怒",              ex: "His irascible temperament made collaboration difficult." },
  { id: 84,  tier: 1, word: "laconic",      phon: "/ləˈkɒnɪk/",        cn: "简洁的，简短的",           root: "Laconia（斯巴达）→ 斯巴达人言简意赅", ex: "His laconic reply to the reviewer's lengthy critique was just two sentences." },
  { id: 85,  tier: 1, word: "laud",         phon: "/lɔːd/",             cn: "赞美，称赞",               root: "laudare（称赞）→ 高度表扬",           ex: "Nature lauded the discovery as the breakthrough of the decade." },
  { id: 86,  tier: 1, word: "loquacious",   phon: "/loʊˈkweɪʃəs/",    cn: "话多的，喋喋不休的",       root: "loqui（说话）→ 说个不停",             ex: "The loquacious panelist monopolized the Q&A session." },
  { id: 87,  tier: 1, word: "lucid",        phon: "/ˈluːsɪd/",          cn: "清晰的，明白易懂的",       root: "lucere（发光）→ 照亮，清晰",          ex: "A lucid abstract allows readers to quickly assess relevance." },
  { id: 88,  tier: 1, word: "magnanimous",  phon: "/mæɡˈnænɪməs/",    cn: "宽宏大量的，慷慨的",       root: "magnus（大）+ animus（心）→ 心胸宽大", ex: "She was magnanimous in crediting her collaborators in the paper." },
  { id: 89,  tier: 1, word: "malleable",    phon: "/ˈmæliəbəl/",       cn: "可塑的，易受影响的",       root: "malleus（锤子）→ 可被锤打成形",       ex: "Young researchers are often more malleable in adopting new paradigms." },
  { id: 90,  tier: 1, word: "mendacious",   phon: "/mɛnˈdeɪʃəs/",      cn: "撒谎的，欺骗的",           root: "mendax（说谎）→ 惯于撒谎",            ex: "The mendacious reporting of results led to a five-year retraction scandal." },
  { id: 91,  tier: 1, word: "mercurial",    phon: "/mɜːrˈkjʊəriəl/",  cn: "变化无常的，反复无常的",   root: "Mercury（信使之神）→ 如水银般流动",   ex: "His mercurial mood swings unsettled the junior members of the team." },
  { id: 92,  tier: 1, word: "misanthrope",  phon: "/ˈmɪsənθroʊp/",    cn: "厌世者，愤世嫉俗者",       root: "misos（恨）+ anthropos（人）→ 恨人类", ex: "The reclusive misanthrope published only sporadically." },
  { id: 93,  tier: 1, word: "mitigate",     phon: "/ˈmɪtɪɡeɪt/",      cn: "减轻，缓和",               root: "mitis（温和）→ 使变温和",             ex: "Blinding participants helped mitigate confirmation bias in the study." },
  { id: 94,  tier: 1, word: "morose",       phon: "/məˈroʊs/",          cn: "阴郁的，沉默寡言的",       root: "morosus（难伺候的）→ 脾气坏，郁郁寡欢", ex: "Repeated rejections left him morose and disengaged from research." },
  { id: 95,  tier: 1, word: "munificent",   phon: "/mjuːˈnɪfɪsənt/",  cn: "慷慨的，大方的",           root: "munus（礼物）+ facere（做）→ 慷慨赠予", ex: "A munificent benefactor endowed the university's AI research center." },
  { id: 96,  tier: 1, word: "nefarious",    phon: "/nɪˈfɛəriəs/",     cn: "极坏的，罪恶的",           root: "nefas（罪行）→ 违法的坏事",           ex: "The nefarious scheme to falsify clinical trial data shocked the community." },
  { id: 97,  tier: 1, word: "exacerbate",   phon: "/ɪɡˈzæsərbeɪt/",  cn: "加剧，使更严重",           root: "ex- + acerbus（苦）→ 使更苦涩",       ex: "The funding cut exacerbated an already strained research environment." },
  { id: 98,  tier: 1, word: "cacophony",    phon: "/kəˈkɒfəni/",       cn: "刺耳的声音，噪音",         root: "kako-（坏）+ phone（声音）→ 难听的声音", ex: "The competing theories created a cacophony that confused the public." },
  { id: 99,  tier: 1, word: "coalesce",     phon: "/ˌkoʊəˈlɛs/",      cn: "联合，合并，融合",         root: "co-（共同）+ alescere（生长）→ 共同成长", ex: "Disparate findings eventually coalesced into a unified theoretical framework." },

  // ══════════════════════════════
  // TIER 2 · 高频（100词）
  // ══════════════════════════════

  { id: 100, tier: 2, word: "obdurate",     phon: "/ˈɒbdjʊrɪt/",      cn: "顽固的，不妥协的",         root: "ob-（对抗）+ durus（坚硬）→ 硬心肠",  ex: "The committee remained obdurate despite compelling evidence to the contrary." },
  { id: 101, tier: 2, word: "obsequious",   phon: "/əbˈsiːkwiəs/",     cn: "奉承的，谄媚的",           root: "ob- + sequi（跟随）→ 跟随讨好",       ex: "His obsequious manner toward senior faculty drew quiet contempt." },
  { id: 102, tier: 2, word: "obstinate",    phon: "/ˈɒbstɪnɪt/",       cn: "固执的，顽固的",           root: "obstinare（坚持）→ 坚持到底",          ex: "She was obstinate in defending her methodology against all criticism." },
  { id: 103, tier: 2, word: "obtuse",       phon: "/əbˈtjuːs/",        cn: "迟钝的，理解缓慢的",       root: "obtundere（打钝）→ 脑子被打钝了",      ex: "The obtuse reviewer failed to grasp the paper's central contribution." },
  { id: 104, tier: 2, word: "opaque",       phon: "/oʊˈpeɪk/",         cn: "不透明的，晦涩的",         root: "opacus（暗的）→ 不透光、不透明",       ex: "The opaque writing style obscured an otherwise valuable analysis." },
  { id: 105, tier: 2, word: "ostracize",    phon: "/ˈɒstrəsaɪz/",      cn: "排斥，放逐",               root: "ostrakon（陶片）→ 古希腊投票放逐制度", ex: "Researchers who challenged the consensus were effectively ostracized." },
  { id: 106, tier: 2, word: "parsimonious", phon: "/ˌpɑːrsɪˈmoʊniəs/", cn: "过度节俭的；（科学）简约的", root: "parcere（节约）→ 吝啬到极点",           ex: "In modeling, a parsimonious explanation is preferred over a complex one." },
  { id: 107, tier: 2, word: "pedantic",     phon: "/pɪˈdæntɪk/",       cn: "卖弄学问的，过分拘泥细节的", root: "pedagogo（教师）→ 过度讲究细节",        ex: "His pedantic focus on formatting distracted from substantive feedback." },
  { id: 108, tier: 2, word: "penchant",     phon: "/ˈpɛnʃənt/",        cn: "强烈爱好，嗜好",           root: "pencher（法语：倾向）→ 倾向某事",      ex: "Her penchant for interdisciplinary research set her work apart." },
  { id: 109, tier: 2, word: "perfidious",   phon: "/pərˈfɪdiəs/",      cn: "背信弃义的，不忠诚的",     root: "per-（违背）+ fides（信任）→ 背叛信任", ex: "The perfidious co-author submitted the paper under his name alone." },
  { id: 110, tier: 2, word: "perfunctory",  phon: "/pərˈfʌŋktəri/",    cn: "敷衍的，马虎的",           root: "per-（彻底）+ fungi（履行）→ 走过场",  ex: "The perfunctory peer review process failed to catch basic errors." },
  { id: 111, tier: 2, word: "pervasive",    phon: "/pərˈveɪsɪv/",      cn: "无处不在的，普遍的",       root: "per-（穿透）+ vadere（走）→ 渗透到处", ex: "Confirmation bias is pervasive in observational research." },
  { id: 112, tier: 2, word: "platitude",    phon: "/ˈplætɪtjuːd/",     cn: "陈词滥调，老生常谈",       root: "plat（平）→ 毫无新意的平淡话",         ex: "The introduction was filled with platitudes rather than precise claims." },
  { id: 113, tier: 2, word: "plethora",     phon: "/ˈplɛθərə/",        cn: "过多，过剩，大量",         root: "plethein（充满）→ 充斥着",             ex: "A plethora of conflicting studies complicated the meta-analysis." },
  { id: 114, tier: 2, word: "polemical",    phon: "/pəˈlɛmɪkəl/",      cn: "好争论的，辩论性的",       root: "polemos（战争）→ 战斗性的论述",         ex: "Her polemical essay challenged the dominant paradigm directly." },
  { id: 115, tier: 2, word: "pragmatic",    phon: "/præɡˈmætɪk/",      cn: "务实的，实用的",           root: "pragma（行为）→ 注重实际行动",          ex: "A pragmatic researcher prioritizes feasible questions over abstract ones." },
  { id: 116, tier: 2, word: "precarious",   phon: "/prɪˈkɛəriəs/",     cn: "不稳定的，危险的",         root: "precari（祈求）→ 靠祈求维持→ 不稳",   ex: "Funding for basic research remains precarious without policy reform." },
  { id: 117, tier: 2, word: "precocious",   phon: "/prɪˈkoʊʃəs/",      cn: "早熟的，过早发育的",       root: "prae-（早）+ coquere（成熟）→ 早熟",  ex: "The precocious student published her first paper at age nineteen." },
  { id: 118, tier: 2, word: "predilection", phon: "/ˌpriːdɪˈlɛkʃən/",  cn: "偏好，偏爱",               root: "prae- + diligere（喜爱）→ 提前喜爱",   ex: "His predilection for qualitative data shaped his entire research agenda." },
  { id: 119, tier: 2, word: "presumptuous", phon: "/prɪˈzʌmptʃuəs/",   cn: "自以为是的，放肆的",       root: "prae-（先）+ sumere（取）→ 提前占有",  ex: "It was presumptuous to claim causation without controlled trials." },
  { id: 120, tier: 2, word: "prevaricate",  phon: "/prɪˈværɪkeɪt/",    cn: "说谎，支吾，含糊其辞",     root: "prae- + varicare（叉开腿）→ 走歪路",   ex: "The spokesperson prevaricated rather than admitting the study's flaw." },
  { id: 121, tier: 2, word: "probity",      phon: "/ˈproʊbɪti/",        cn: "正直，廉洁",               root: "probus（诚实的）→ 道德高尚",           ex: "His probity in reporting negative results enhanced his credibility." },
  { id: 122, tier: 2, word: "prodigal",     phon: "/ˈprɒdɪɡəl/",       cn: "挥霍的，浪费的",           root: "prodigere（消耗）→ 挥霍浪费",          ex: "The prodigal use of compute resources raised sustainability concerns." },
  { id: 123, tier: 2, word: "prodigious",   phon: "/prəˈdɪdʒəs/",      cn: "巨大的，惊人的，了不起的", root: "prodigium（神迹）→ 大得令人惊叹",       ex: "She produced a prodigious volume of work in her first decade." },
  { id: 124, tier: 2, word: "proliferate",  phon: "/prəˈlɪfəreɪt/",    cn: "激增，扩散",               root: "proles（后代）+ ferre（带来）→ 大量繁殖", ex: "Preprint servers have caused research findings to proliferate rapidly." },
  { id: 125, tier: 2, word: "propitious",   phon: "/prəˈpɪʃəs/",       cn: "有利的，吉祥的",           root: "propitius（友善的）→ 条件有利",         ex: "The political climate proved propitious for science funding reform." },
  { id: 126, tier: 2, word: "prosaic",      phon: "/prəˈzeɪɪk/",        cn: "平淡的，乏味的，平庸的",   root: "prosa（散文）→ 平铺直叙，缺乏诗意",    ex: "His prosaic writing style undermined an otherwise original thesis." },
  { id: 127, tier: 2, word: "provincial",   phon: "/prəˈvɪnʃəl/",       cn: "狭隘的，地方性的",         root: "provincia（省）→ 局限于一省之见",       ex: "A provincial outlook limited his awareness of global research trends." },
  { id: 128, tier: 2, word: "prudent",      phon: "/ˈpruːdənt/",        cn: "谨慎的，有远见的",         root: "providere（预见）→ 有先见之明",         ex: "It is prudent to pre-register hypotheses before data collection." },
  { id: 129, tier: 2, word: "querulous",    phon: "/ˈkwɛrʊləs/",        cn: "抱怨的，爱发牢骚的",       root: "queri（抱怨）→ 总在抱怨",              ex: "The querulous reviewer complained about every aspect of the paper." },
  { id: 130, tier: 2, word: "quixotic",     phon: "/kwɪkˈsɒtɪk/",      cn: "不切实际的，空想的",       root: "Don Quixote（唐吉诃德）→ 浪漫但脱离现实", ex: "His quixotic plan to cure all diseases within a decade drew skepticism." },
  { id: 131, tier: 2, word: "rancor",       phon: "/ˈræŋkər/",          cn: "深切的怨恨，长期怨恨",     root: "rancere（腐烂）→ 怨恨腐蚀内心",        ex: "Years of priority disputes fueled a rancor that divided the field." },
  { id: 132, tier: 2, word: "recalcitrant", phon: "/rɪˈkælsɪtrənt/",   cn: "不服从的，难管的",         root: "re- + calcitrare（踢）→ 不停踢腿反抗", ex: "The recalcitrant participant skewed the trial's results significantly." },
  { id: 133, tier: 2, word: "rectify",      phon: "/ˈrɛktɪfaɪ/",        cn: "纠正，改正",               root: "rectus（直）+ facere（做）→ 弄直",     ex: "The authors issued a correction to rectify the computational error." },
  { id: 134, tier: 2, word: "reticent",     phon: "/ˈrɛtɪsənt/",        cn: "沉默寡言的，不愿透露的",   root: "reticere（沉默）→ 保持沉默",           ex: "He was reticent about sharing unpublished data with competitors." },
  { id: 135, tier: 2, word: "rife",         phon: "/raɪf/",              cn: "充满的，盛行的",           root: "ryfe（古英语：普遍的）→ 广泛存在",     ex: "The subfield was rife with methodological inconsistencies." },
  { id: 136, tier: 2, word: "rigorous",     phon: "/ˈrɪɡərəs/",         cn: "严格的，严密的，彻底的",   root: "rigor（僵硬）→ 要求严格不放松",         ex: "Rigorous experimental controls are essential for valid inference." },
  { id: 137, tier: 2, word: "ruminate",     phon: "/ˈruːmɪneɪt/",       cn: "深思，反复考虑",           root: "rumen（反刍胃）→ 像牛一样反刍/反复想",  ex: "She ruminated for months before submitting the revised manuscript." },
  { id: 138, tier: 2, word: "sagacious",    phon: "/səˈɡeɪʃəs/",        cn: "睿智的，有洞察力的",       root: "sagire（感知）→ 感知力强",              ex: "Her sagacious advice guided junior researchers through their first studies." },
  { id: 139, tier: 2, word: "salient",      phon: "/ˈseɪliənt/",        cn: "显著的，最重要的",         root: "salire（跳）→ 跳出来最显眼",           ex: "The most salient finding was a 40% reduction in error rate." },
  { id: 140, tier: 2, word: "sanctimonious", phon: "/ˌsæŋktɪˈmoʊniəs/", cn: "假装圣洁的，伪善的",      root: "sanctus（神圣）+ monere（提醒）→ 表演虔诚", ex: "His sanctimonious lecture on research ethics rang hollow given his conduct." },
  { id: 141, tier: 2, word: "sardonic",     phon: "/sɑːrˈdɒnɪk/",       cn: "嘲讽的，讽刺的",           root: "Sardinia（撒丁岛）→ 该岛植物使人面部抽搐→ 苦笑", ex: "Her sardonic footnotes delighted readers but infuriated the authors she cited." },
  { id: 142, tier: 2, word: "scrupulous",   phon: "/ˈskruːpjʊləs/",     cn: "一丝不苟的，道德上谨慎的", root: "scrupulus（小石子）→ 良心上的细小顾虑", ex: "Scrupulous record-keeping allowed the team to reproduce every experiment." },
  { id: 143, tier: 2, word: "skeptical",    phon: "/ˈskɛptɪkəl/",       cn: "怀疑的，持怀疑态度的",     root: "skeptikos（思考者）→ 爱质疑的人",      ex: "Reviewers were skeptical of the extraordinary effect size reported." },
  { id: 144, tier: 2, word: "soporific",    phon: "/ˌsɒpəˈrɪfɪk/",      cn: "催眠的，令人昏昏欲睡的",   root: "sopor（深睡）+ facere（使）→ 使人入睡", ex: "The soporific delivery undermined an otherwise compelling presentation." },
  { id: 145, tier: 2, word: "specious",     phon: "/ˈspiːʃəs/",         cn: "似是而非的，外表好看实则错误的", root: "speciosus（外表好看）→ 表面合理但实则错", ex: "The argument was specious: logically structured yet fundamentally flawed." },
  { id: 146, tier: 2, word: "spurious",     phon: "/ˈspjʊəriəs/",       cn: "伪造的，假的，错误的",     root: "spurius（私生子）→ 非正统，假冒的",    ex: "The correlation was spurious, explained entirely by a third variable." },
  { id: 147, tier: 2, word: "stolid",       phon: "/ˈstɒlɪd/",          cn: "感情不外露的，木然的",     root: "stolidus（迟钝）→ 表情木然，淡然",      ex: "His stolid demeanor during the defense concealed his anxiety." },
  { id: 148, tier: 2, word: "strident",     phon: "/ˈstraɪdənt/",       cn: "刺耳的，强硬的",           root: "stridere（嘎吱响）→ 声音刺耳",         ex: "His strident criticism of the peer-review system divided colleagues." },
  { id: 149, tier: 2, word: "subvert",      phon: "/səbˈvɜːrt/",        cn: "颠覆，破坏",               root: "sub-（下）+ vertere（转）→ 从下面翻转", ex: "The findings subverted decades of conventional wisdom in the field." },
  { id: 150, tier: 2, word: "succinct",     phon: "/səkˈsɪŋkt/",        cn: "简洁的，言简意赅的",       root: "sub- + cingere（束紧）→ 紧缩语言",     ex: "Journals prize succinct abstracts that convey findings in under 250 words." },
  { id: 151, tier: 2, word: "supercilious", phon: "/ˌsuːpərˈsɪliəs/",   cn: "傲慢的，目中无人的",       root: "super-（上）+ cilium（眉毛）→ 眉毛上扬",  ex: "His supercilious attitude alienated potential collaborators." },
  { id: 152, tier: 2, word: "sycophant",    phon: "/ˈsɪkəfænt/",        cn: "马屁精，谄媚者",           root: "syko（无花果）+ phainein（显示）→ 告密者→ 阿谀奉承", ex: "Surrounded by sycophants, the department head received no honest feedback." },
  { id: 153, tier: 2, word: "taciturn",     phon: "/ˈtæsɪtɜːrn/",       cn: "沉默寡言的，寡言少语的",   root: "tacere（沉默）→ 习惯性沉默",           ex: "The taciturn statistician communicated mainly through meticulously drafted emails." },
  { id: 154, tier: 2, word: "tangential",   phon: "/tænˈdʒɛnʃəl/",      cn: "切线的，不相关的，离题的", root: "tangere（接触）→ 只是擦边",             ex: "The anecdote was tangential and weakened the paper's focus." },
  { id: 155, tier: 2, word: "tenacious",    phon: "/təˈneɪʃəs/",        cn: "坚韧不拔的，顽强的",       root: "tenere（持有）→ 牢牢抓住，不放弃",      ex: "Tenacious pursuit of negative results is as valuable as positive findings." },
  { id: 156, tier: 2, word: "tendentious",  phon: "/tɛnˈdɛnʃəs/",       cn: "有偏见的，带倾向性的",     root: "tendere（倾向）→ 明显向一边倒",         ex: "A tendentious framing of the data misled readers about the conclusions." },
  { id: 157, tier: 2, word: "terse",        phon: "/tɜːrs/",             cn: "简洁的，简短而直接的",     root: "tersus（擦干净）→ 去掉多余，简练",      ex: "His terse response to the criticism made clear he would not revise." },
  { id: 158, tier: 2, word: "torpid",       phon: "/ˈtɔːrpɪd/",         cn: "迟缓的，麻木的，无精打采的", root: "torpere（僵硬）→ 失去活力",              ex: "Years of routine work left the research team torpid and uncreative." },
  { id: 159, tier: 2, word: "tractable",    phon: "/ˈtræktəbəl/",       cn: "顺从的，易处理的",         root: "trahere（拉）→ 可以拉动，好操控",       ex: "Tractable mathematical problems are often prioritized over important ones." },
  { id: 160, tier: 2, word: "trenchant",    phon: "/ˈtrɛntʃənt/",       cn: "犀利的，一针见血的",       root: "trencher（切割）→ 切入核心",            ex: "Her trenchant critique forced a fundamental rethinking of the model." },
  { id: 161, tier: 2, word: "trite",        phon: "/traɪt/",             cn: "陈腐的，老套的",           root: "terere（磨）→ 被磨得没有新鲜感",        ex: "The conclusion relied on trite generalizations rather than specific claims." },
  { id: 162, tier: 2, word: "truculent",    phon: "/ˈtrʌkjʊlənt/",      cn: "好斗的，粗暴的，不服从的", root: "truculentus（凶猛）→ 咄咄逼人",         ex: "The truculent reviewer demanded revisions that contradicted each other." },
  { id: 163, tier: 2, word: "vacillate",    phon: "/ˈvæsɪleɪt/",        cn: "摇摆不定，犹豫",           root: "vacillare（摇晃）→ 前后摇摆，拿不定主意", ex: "She vacillated between two competing theoretical frameworks for months." },
  { id: 164, tier: 2, word: "venerate",     phon: "/ˈvɛnəreɪt/",        cn: "崇敬，尊敬",               root: "venerari（崇拜）→ 充满敬意",            ex: "Students venerated the pioneer whose model underpinned the entire subfield." },
  { id: 165, tier: 2, word: "verbose",      phon: "/vɜːrˈboʊs/",        cn: "冗长的，啰嗦的",           root: "verbum（话）→ 话太多了",               ex: "The verbose manuscript was returned for substantial condensation." },
  { id: 166, tier: 2, word: "vestigial",    phon: "/vɛˈstɪdʒɪəl/",      cn: "退化的，残余的",           root: "vestigium（痕迹）→ 演化遗留的痕迹",    ex: "The vestigial regulatory pathway no longer performs its original function." },
  { id: 167, tier: 2, word: "virulent",     phon: "/ˈvɪrʊlənt/",        cn: "毒性强的，猛烈的，激烈的", root: "virus（毒素）→ 毒性极强",               ex: "A virulent strain of the pathogen emerged following antibiotic exposure." },
  { id: 168, tier: 2, word: "volatile",     phon: "/ˈvɒlətaɪl/",        cn: "不稳定的，易变的，挥发性的", root: "volare（飞）→ 飘忽不定",                ex: "The volatile political environment made longitudinal funding unreliable." },
  { id: 169, tier: 2, word: "voracious",    phon: "/vəˈreɪʃəs/",        cn: "贪婪的，如饥似渴的",       root: "vorare（吞噬）→ 狼吞虎咽",             ex: "Her voracious reading habit spanned five disciplines simultaneously." },
  { id: 170, tier: 2, word: "zealous",      phon: "/ˈzɛləs/",            cn: "热心的，充满热情的",       root: "zelos（热忱）→ 充满热忱",              ex: "A zealous but untrained researcher can introduce unintentional bias." },
  { id: 171, tier: 2, word: "acrimony",     phon: "/ˈækrɪməni/",        cn: "刻薄，尖刻，激烈争论",     root: "acer（尖锐）→ 说话尖锐刻薄",            ex: "The acrimony between the two labs prevented fruitful collaboration." },
  { id: 172, tier: 2, word: "anachronism",  phon: "/əˈnækrənɪzəm/",     cn: "时代错误，不合时宜的事物", root: "ana-（反）+ chronos（时间）→ 时间错位",  ex: "Citing a 1980s textbook as primary evidence is an anachronism in AI research." },
  { id: 173, tier: 2, word: "anodyne",      phon: "/ˈænədaɪn/",         cn: "无害的，不刺激的；镇痛剂", root: "an-（无）+ odynē（痛）→ 止痛，不引发反应", ex: "The committee issued an anodyne statement that satisfied no one." },
  { id: 174, tier: 2, word: "apposite",     phon: "/ˈæpəzɪt/",          cn: "贴切的，恰当的",           root: "ad-（对）+ ponere（放）→ 放在合适位置", ex: "Her apposite choice of examples clarified an otherwise abstract concept." },
  { id: 175, tier: 2, word: "bucolic",      phon: "/bjuːˈkɒlɪk/",       cn: "田园的，乡村的",           root: "boukolos（牧人）→ 牧歌式的田园生活",   ex: "He retreated to a bucolic setting to finish writing his dissertation." },
  { id: 176, tier: 2, word: "compunction",  phon: "/kəmˈpʌŋkʃən/",      cn: "内疚，悔恨",               root: "com- + pungere（刺）→ 良心上被刺痛",   ex: "She felt compunction after omitting contradicting data from the report." },
  { id: 177, tier: 2, word: "derivative",   phon: "/dɪˈrɪvətɪv/",       cn: "缺乏创意的，衍生的",       root: "derivare（引流）→ 从他处引来，非原创",  ex: "Reviewers criticized the paper as too derivative of earlier seminal works." },
  { id: 178, tier: 2, word: "desiccate",    phon: "/ˈdɛsɪkeɪt/",        cn: "使干燥，使枯竭",           root: "de- + siccus（干）→ 彻底干燥",          ex: "Poor archiving practices desiccated the institutional memory of the lab." },
  { id: 179, tier: 2, word: "dilettante",   phon: "/ˌdɪlɪˈtænti/",      cn: "浅尝者，业余爱好者",       root: "dilettare（意大利语：喜爱）→ 只是爱好，非专业", ex: "A dilettante's enthusiasm cannot substitute for disciplined training." },
  { id: 180, tier: 2, word: "duplicity",    phon: "/djuːˈplɪsɪti/",     cn: "欺骗，口是心非",           root: "duplex（双重）→ 双面人",               ex: "His duplicity in reporting methods was exposed during the audit." },
  { id: 181, tier: 2, word: "endemic",      phon: "/ɛnˈdɛmɪk/",         cn: "地方性的，某地区特有的",   root: "en-（在）+ demos（人民）→ 在当地人群中", ex: "Data fabrication appears to be endemic in certain research environments." },
  { id: 182, tier: 2, word: "enervate",     phon: "/ˈɛnərveɪt/",        cn: "使精力衰竭，使虚弱",       root: "e-（去除）+ nervus（神经）→ 抽掉力气",  ex: "The relentless grant cycle enervated even the most passionate researchers." },
  { id: 183, tier: 2, word: "enigmatic",    phon: "/ˌɛnɪɡˈmætɪk/",      cn: "神秘的，难以理解的",       root: "ainigma（谜语）→ 像谜一样",             ex: "The mechanism underlying the effect remained enigmatic for two decades." },
  { id: 184, tier: 2, word: "facetious",    phon: "/fəˈsiːʃəs/",         cn: "爱开玩笑的，不认真的",     root: "facetus（风趣的）→ 对严肃事物轻浮对待", ex: "His facetious response to a legitimate methodological concern was off-putting." },
  { id: 185, tier: 2, word: "felicitous",   phon: "/fɪˈlɪsɪtəs/",       cn: "恰当的，贴切的，幸福的",   root: "felicitas（幸福）→ 措辞恰到好处",       ex: "A felicitous phrase can make even dense technical content accessible." },
  { id: 186, tier: 2, word: "forestall",    phon: "/fɔːrˈstɔːl/",        cn: "预先阻止，提前阻止",       root: "fore-（预先）+ stall（停止）→ 提前拦截", ex: "Pre-registration can forestall post-hoc hypothesis invention." },
  { id: 187, tier: 2, word: "aggrandize",   phon: "/əˈɡrændaɪz/",       cn: "夸大，吹捧，扩大权势",     root: "ad- + grandis（大）→ 人为放大",         ex: "He tended to aggrandize his role in collaborative projects." },
  { id: 188, tier: 2, word: "ostensible",   phon: "/ɒˈstɛnsɪbəl/",      cn: "表面上的，看似的",         root: "ostendere（展示）→ 展示给人看的（不一定是真的）", ex: "The ostensible purpose of the meeting was collaboration; the real motive was recruitment." },
  { id: 189, tier: 2, word: "inveterate",   phon: "/ɪnˈvɛtərɪt/",       cn: "根深蒂固的，积习难改的",   root: "in- + vetus（老）→ 老习惯根深蒂固",    ex: "He was an inveterate skeptic, questioning every published finding." },
  { id: 190, tier: 2, word: "lassitude",    phon: "/ˈlæsɪtjuːd/",       cn: "疲倦，无精打采，倦怠",     root: "lassus（疲倦的）→ 身心俱疲",            ex: "Academic lassitude set in after five years without a major breakthrough." },
  { id: 191, tier: 2, word: "lethargy",     phon: "/ˈlɛθədʒi/",         cn: "昏昏欲睡，无精打采",       root: "lethe（遗忘之河）+ argos（懒惰）→ 像被遗忘了一样", ex: "Institutional lethargy slowed the adoption of open-science practices." },
  { id: 192, tier: 2, word: "levity",       phon: "/ˈlɛvɪti/",           cn: "轻率，轻浮",               root: "levis（轻）→ 对严肃事物过于轻描淡写",  ex: "His levity during the defense undermined the committee's confidence in him." },
  { id: 193, tier: 2, word: "mollify",      phon: "/ˈmɒlɪfaɪ/",         cn: "安抚，平息",               root: "mollis（软）+ facere（做）→ 软化",      ex: "The editor offered additional time to mollify the frustrated authors." },
  { id: 194, tier: 2, word: "notorious",    phon: "/noʊˈtɔːriəs/",      cn: "臭名昭著的",               root: "notus（知名的）→ 以坏名声闻名",         ex: "The lab became notorious for its aggressive hiring tactics." },
  { id: 195, tier: 2, word: "nuance",       phon: "/ˈnjuːɑːns/",        cn: "细微差别，微妙之处",       root: "nuer（法语：显示细微差别）→ 微妙的区别", ex: "A nuanced reading of the data reveals a more complex pattern." },
  { id: 196, tier: 2, word: "opprobrium",   phon: "/əˈproʊbriəm/",      cn: "强烈谴责，耻辱",           root: "ob-（反对）+ probrum（耻辱的行为）",    ex: "The retraction attracted widespread opprobrium from the research community." },
  { id: 197, tier: 2, word: "petulant",     phon: "/ˈpɛtʃʊlənt/",       cn: "脾气坏的，无理取闹的",     root: "petere（要求）→ 要求不满就发脾气",       ex: "His petulant reaction to criticism signaled an unwillingness to improve." },
  { id: 198, tier: 2, word: "recondite",    phon: "/ˈrɛkəndaɪt/",       cn: "晦涩的，鲜为人知的",       root: "recondere（隐藏）→ 藏起来的知识",        ex: "The paper's recondite references were inaccessible to most readers." },
  { id: 199, tier: 2, word: "unequivocal",  phon: "/ˌʌnɪˈkwɪvəkəl/",   cn: "明确的，毫无疑义的",       root: "un- + equivocal（含糊的）→ 不含糊",     ex: "The evidence provided unequivocal support for the proposed mechanism." },
];
